---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: frigate
  namespace: home-automation
  annotations:
    fluxcd.io/ignore: "false"
    fluxcd.io/automated: "false"
spec:
  releaseName: frigate
  chart:
    repository: https://billimek.com/billimek-charts/
    name: frigate
    version: 3.2.0
  values:
    image:
      repository: blakeblackshear/frigate
      tag: 0.5.2

    affinity:
      nodeAffinity:
        requiredDuringSchedulingIgnoredDuringExecution:
          nodeSelectorTerms:
            - matchExpressions:
                - key: feature.node.kubernetes.io/custom-coral-tpu
                  operator: In
                  values:
                    - "true"

    podAnnotations:
      configmap.reloader.stakater.com/reload: "frigate,frigate-masks"

    timezone: Europe/Amsterdam

    coral:
      enabled: true

    masksConfigMap: frigate-masks

  valuesFrom:
    - secretKeyRef:
        name: frigate-helm-values
        key: values
