---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: frigate
  namespace: home-automation
  annotations:
    fluxcd.io/ignore: "false"
    fluxcd.io/automated: "false"
spec:
  releaseName: frigate
  chart:
    repository: https://billimek.com/billimek-charts/
    name: frigate
    version: 3.2.0
  values:
    image:
      repository: blakeblackshear/frigate
      tag: 0.5.2

    affinity:
      nodeAffinity:
        requiredDuringSchedulingIgnoredDuringExecution:
          nodeSelectorTerms:
            - matchExpressions:
                - key: feature.node.kubernetes.io/usb-ff_18d1_9302.present
                  operator: In
                  values:
                    - "true"

    podAnnotations:
      configmap.reloader.stakater.com/reload: "frigate,frigate-masks"

    timezone: Europe/Amsterdam

    coral:
      enabled: true

    masksConfigMap: frigate-masks
    extraSecretForEnvFrom:
      - frigate-secrets

    config: |
      #################
      ## Environment variables that begin with 'FRIGATE_' may be referenced in {}.
      ##   password: '{FRIGATE_MQTT_PASSWORD}'
      #################
      web_port: 5000

      mqtt:
        host: {FRIGATE_MQTT_HOST}
        port: {FRIGATE_MQTT_PORT}
        topic_prefix: frigate
        user: {FRIGATE_MQTT_USER}
        password: {FRIGATE_MQTT_PASSWORD}
        # client_id: frigate # Optional -- set to override default client id of 'frigate' if running multiple instances
        # password: password # Optional

      #################
      # Default ffmpeg args. Optional and can be overwritten per camera.
      # Should work with most RTSP cameras that send h264 video
      # Built from the properties below with:
      # "ffmpeg" + global_args + input_args + "-i" + input + output_args
      #################
      # ffmpeg:
      #   global_args:
      #     - -hide_banner
      #     - -loglevel
      #     - panic
      #   hwaccel_args: []
      #   input_args:
      #     - -avoid_negative_ts
      #     - make_zero
      #     - -fflags
      #     - nobuffer
      #     - -flags
      #     - low_delay
      #     - -strict
      #     - experimental
      #     - -fflags
      #     - +genpts+discardcorrupt
      #     - -vsync
      #     - drop
      #     - -rtsp_transport
      #     - tcp
      #     - -stimeout
      #     - '5000000'
      #     - -use_wallclock_as_timestamps
      #     - '1'
      #   output_args:
      #     - -f
      #     - rawvideo
      #     - -pix_fmt
      #     - rgb24

      ####################
      # Global object configuration. Applies to all cameras
      # unless overridden at the camera levels.
      # Keys must be valid labels. By default, the model uses coco (https://dl.google.com/coral/canned_models/coco_labels.txt).
      # All labels from the model are reported over MQTT. These values are used to filter out false positives.
      # min_area (optional): minimum width*height of the bounding box for the detected person
      # max_area (optional): maximum width*height of the bounding box for the detected person
      # threshold (optional): The minimum decimal percentage (50% hit = 0.5) for the confidence from tensorflow
      ####################
      objects:
        track:
          - person
        filters:
          person:
            min_area: 5000
            max_area: 100000
            threshold: 0.5

      cameras:
        frontdoor:
          ffmpeg:
            ################
            # Source passed to ffmpeg after the -i parameter. Supports anything compatible with OpenCV and FFmpeg.
            # Environment variables that begin with 'FRIGATE_' may be referenced in {}
            ################
            input: {FRIGATE_CAMERA_URL}
            #################
            # These values will override default values for just this camera
            #################
            # global_args: []
            # hwaccel_args: []
            # input_args: []
            # output_args: []

          ################
          ## Optionally specify the resolution of the video feed. Frigate will try to auto detect if not specified
          ################
          # height: 1280
          # width: 720

          ################
          ## Optional mask. Must be the same aspect ratio as your video feed.
          ##
          ## The mask works by looking at the bottom center of the bounding box for the detected
          ## person in the image. If that pixel in the mask is a black pixel, it ignores it as a
          ## false positive. In my mask, the grass and driveway visible from my backdoor camera
          ## are white. The garage doors, sky, and trees (anywhere it would be impossible for a
          ## person to stand) are black.
          ##
          ## Masked areas are also ignored for motion detection.
          ################
          mask: frontdoor-mask.bmp

          ################
          # Allows you to limit the framerate within frigate for cameras that do not support
          # custom framerates. A value of 1 tells frigate to look at every frame, 2 every 2nd frame,
          # 3 every 3rd frame, etc.
          ################
          take_frame: 1

          ################
          # Configuration for the snapshots in the debug view and mqtt
          ################
          snapshots:
            show_timestamp: True

          ################
          # Camera level object config. This config is merged with the global config above.
          ################
          objects:
            track:
              - person
            filters:
              person:
                min_area: 5000
                max_area: 100000
                threshold: 0.5

    valuesFrom:
      - secretKeyRef:
          name: frigate-helm-values
          key: values
