---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: frigate
  namespace: home-automation
  annotations:
    fluxcd.io/ignore: "false"
    fluxcd.io/automated: "false"
spec:
  releaseName: frigate
  chart:
    repository: https://k8s-at-home.com/charts/
    name: frigate
    version: 4.0.0

  valuesFrom:
  - secretKeyRef:
      name: frigate-helm-values
      key: values.yaml
