---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: nzbget
  namespace: downloads
  annotations:
    fluxcd.io/ignore: "false"
    fluxcd.io/automated: "false"
spec:
  releaseName: nzbget
  chart:
    repository: https://k8s-charts.juggels.online
    name: nzbget
    version: 1.0.0
  values:
    image:
      repository: linuxserver/nzbget
      tag: "v21.0-ls61"

    config:
      timezone: "Europe/Amsterdam"
      uid: 1031
      gid: 100

    autoscaling:
      enabled: true
      minReplicas: 1
      maxReplicas: 1

    persistence:
      enabled: true

    extraVolumes:
      - name: nas-media
        persistentVolumeClaim:
          claimName: nfs-nas-media
        mountPath: "/data/nas-media"

    ingress:
      enabled: true
      annotations:
        kubernetes.io/ingress.class: nginx
        cert-manager.io/cluster-issuer: bjws-lan-ca-issuer
        nginx.ingress.kubernetes.io/proxy-body-size: 25m

    resources:
      requests:
        memory: "128M"
      limits:
        memory: "512M"

    probes:
      liveness:
        initialDelaySeconds: 0
      readiness:
        initialDelaySeconds: 0
      startup:
        enabled: true

  valuesFrom:
    - secretKeyRef:
        name: nzbget-helm-values
        key: values
