---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: nzbget
  namespace: downloads
  annotations:
    fluxcd.io/ignore: "false"
    fluxcd.io/automated: "false"
spec:
  releaseName: nzbget
  chart:
    repository: https://k8s-charts.juggels.online
    name: nzbget
    version: 1.0.0

  valuesFrom:
    - secretKeyRef:
        name: nzbget-helm-values
        key: values
