---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: nzbget
  namespace: downloads
  annotations:
    fluxcd.io/ignore: "false"
    fluxcd.io/automated: "false"
spec:
  releaseName: nzbget
  chart:
    repository: https://k8s-at-home.com/charts/
    name: nzbget
    version: 5.0.0

  values:
    nzbget:
      image:
        organization: linuxserver
        repository: nzbget
        tag: "v21.0-ls61"

  valuesFrom:
    - secretKeyRef:
        name: nzbget-helm-values
        key: values.yaml
