---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: nzbget-helm-values
  namespace: downloads
spec:
  encryptedData:
    values: AgAiryj2Erq1KSWYTRSI6HcKvK8DybsCLmtVRyfQhOu4hvoswaxQ10tQc30v/cC4fvQhJvhzBzmFRb5iHn7EfAsyD+/wwl+5zTcWzXPYP6adR+dmFr0arpLaxhcu1O1F78bjsNj53Q+3PdNa56OLG23au9/wco0kZGTPn1MJZ+n+6GBRifioSAhjwBYu1e6vWrBSFjxOOtMwB2QUU3pogGvjnBvhDpF3eYQAFaGGLKqcCGFberdomGr8GA9B9k+euDJe3sB8qW331jb8O0297M9Z4BuvRqu3k8vqZBD6h7zbAxYV7H/Zulfn8YBEkRXmFb0uRLWVmnTVFZ5nV1X9SvCkCuSDV/Jtv27CPVNAug8N61zr8ou33TcxB2/QAVETN3EcgZKy+FCILH2ZSNrLqzXK61qFwh8OJ0/Xta9UPASOTTXUUumKryRrwiZ1X0SEbM9VkCDWl91x92GIHrpY7pfcszlNU64C/82pje7ZK8gcq8y+ESOp6R88sdym8m3pAzbR7H132qo39wxrf2njbMiWDYtCcE4afZM60ej34zzBFD+u7YbPZO/IOm5HO+zYddA7RLPKhe7BjIIrmTdZTy86hjkQUt1k6YW6BgIPKv7xnnN0z8rKQNlEIgm4Vx4Ec0B+krKYJXoPQ06ZzjjG34GkH0TqLjhXNwoCS07qlQMJRSVmmfwgaxkbNGbVKHmXnwYBc2D3rJHoVypD0xt4Z7bDaMNClNtt39fm/3dAxYGenpKfbFjN1D3JDOTsLjDGRtVbQsVP/FyKMe8apCjWSIupTbW7vxDCT/9SnB6XOWESMRzPvae1zQ67IWdl7kprtDbFZTXI8psu2qZuMaUq5F/QRy7dw0ueICZMA+uaw2y+ZyFf0t/brBuwIX/gby3ztb2pmWca
  template:
    metadata:
      name: nzbget-helm-values
      namespace: downloads
    type: Opaque
