---
ignore: |
  .secrets/
  ansible/

extends: default

rules:
  line-length: disable
  comments:
    min-spaces-from-content: 1

  truthy:
    allowed-values: ['true', 'false', 'on', 'yes']

  indentation:
    spaces: 2
    indent-sequences: consistent
