---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: deconz
  namespace: home-automation
  annotations:
    fluxcd.io/ignore: "false"
    fluxcd.io/automated: "false"
spec:
  releaseName: deconz
  chart:
    repository: https://k8s-at-home.com/charts/
    name: deconz
    version: 2.0.0

  valuesFrom:
    - secretKeyRef:
        name: deconz-helm-values
        key: values.yaml
