apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: deconz-helm-values
  namespace: home-automation
spec:
  encryptedData:
    values: AgBo/o8ric/GyYIJ4e4BBmu1n3OBdVuK+ZVBvcWIEZhXIZW8aqyRiRtMJY5WUXZ+8OdpCyagOzawWxR9ms78ZAyY28GryjSi4n9LeuNXPVDXUKafNRbI//fF2phlNnRlj1svMlKJ9n59Yjr02dKTcXLOJo9rJoniTXFVf3m6QCy9Jzzf7QQqtkK4hmCx0rKsb92x6pO10vD0KHcB+hYMxAaO+ID1BFOiMlkVVwFoNTzWIlZywnVJ1MraZokCUWy3xoMdRdyCV9XrclgShrcCUT8Pxwp+93+2nwk5UlBYZkT+3yRsRbtbIv2ihzcWkjxrzimTnPZ6qBOEX61uIfWlW838jZt7EO6CfsDY6ERFCQQEvl0LbxMDYwMGcZpxYTzwnkOeIHPh47E6zIZjO14C9NOlHt/iadACWBWH40RaHpBsCrjP2gGDMWhHlIvfo1+JmykYnSsdLxb6dMAVK9kVTUXK8lw1YBW5WNmp4rYW6VSpQzTBLxNjEDCMXKFAE985aFy20arFgGIQtgw6CrzNCyHOz3ljYIUfMdLN6Rpx9m52kk4vdxzFA10N2WNwjdEXUGbsx9iDaxvfLwoPDhkgF71VK6VXX8nhIHIYYpKp5yMl3Tp10ZNghI3DmtFcJD1cJst9zbMYtWEJGsgBYKWribQA7Nd5sxSzn+dmlJF/uLgf1ihzwhGTu0r2Dix10sx8aJl/HFUjBTuEKDaVMotN6DqCL/XiHEPy52Jghg==
  template:
    metadata:
      name: deconz-helm-values
      namespace: home-automation
    type: Opaque
