apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: deconz-helm-values
  namespace: home-automation
spec:
  encryptedData:
    values: AgB3uixEZoNRYNGap15d+ZlbcMd840WkwxCTJoADirkN0sJjiLYyO86AJ/hxIhlVQaBrNePDCH/a0+ToISLImXS+FVDfiKWUwJEKURITVPZTkn5F7vsPW0btO9IgZbnoYS0JgxQCmfvawe91oEwCbUbzrbEksoG4zgXBJfrMXXRbN2cUu3hxsH24H/hBPhzq/WF/fh8gcIAwNeqTK4Ra5/1rcQ6bIeT5zkCdtj8FhEO0zkFc48st4WBUdgL7g7SaRYtUBOFvzOJ9IoJyekfROHbFBEx8ekNikTQ+fl6vjc3JY8YE9I1ijIv1McN99Gp5xiMJdG4NBJs1c4Lbc3CjDNfAQUzEft/wSOwf98uqbsAwd3h9ecS+WOYNvm25LxflFTixv5XPP0Z4oLf01ca/ifyROaMWz2Kb0lLGfMynlh+vkvZv05ZcoDH8j8+0LGxGFYt7KxeX1HO2VniPF66ulzpy9uA5r24XCxafnLKb5yS3JqDWS+QeU7FcDk+9x24GSTtaMmRLZbfKcqG0Nf7c1WH/LPTwRseQ6J/0DW3sxQCOemDN+S6OyG31/E6XfsMyXtxdKj70vB0rCw5RCeh9WS0Hs+YsVTTvjyUoArWfICqQ/Cr2KPLs4H5gzwLajqxkHKcgHbmQVGNiFQgNOtTvV2dNA2xnPqTJlRp+Cct+/mxzqV1c9BOfMjCJRjZJK7/GGLUno4FOVBgI6d1fsQAj1hJOraMzS8O84QcTlQ==
  template:
    metadata:
      name: deconz-helm-values
      namespace: home-automation
    type: Opaque
