apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: deconz-helm-values
  namespace: home-automation
spec:
  encryptedData:
    values: AgBQAm3gEOF2JEWcLe3cYr88txZWmu2MCYLgwvJzjdV3AWiZwC69WyyNiIKQFHm7gC3cj+FVWct8X2Oq1+2REMUbe8W0p0TNfjVdJc8kFcgUO2h3x2GgOIiKfrDR+vQAHiaSzslMO2HA3Qv92/oXgm8KZI3zvBfRFlI5K3LmYt6qnE5zowiAI89J9qLYrGH3gTEPn5nElXTxR8ayYaqu34qEeZaB6LgwNen2DAgvqfmODLFMXDOxrWGTRkdfBYx38hkmQe+UlV4K1s5HvGnGX3Wz/psJgvLmYzPSLT1mKqpCecQjXSs4pIbh8gEfVqUNybVq/d7uRfAaOjvVW/QPOMLNY6jBOoQYZW8Zp84AiD4EnB6zuHz4ukkOYJUTpMKOO1PKwbdL6XgBYL9fPQgEgU+n7IEjrVlBNu43Xbjmyqv35fk2AMthWJs/Xq0tlKFJX9QCs4Ux2eUaPKzxm/EOtkkNRqNecG6bJ22+e1AjJ5pvLCLcssoKzNEtxzcBQGYJvOthWNKBGMQmOrD+iuNrkgTdS8gTFgluC/yPHQfphfKszng8SFdVo17xzkxBclORPYs4O5T/1Zb5ltysL1eb16JIg6UThF/B3qcnV6xCvFJfuOb4lkLDzG72gjTfTVcAKCUTBX57jgRwBagLIpPtbYl0jr8KdkakBajJGUK9xzAkNCMe9TaqhN72LVD6oy3rKCH3NOjsocrj+OvvG4U68/Kkp9SEHjhHzlONjw==
  template:
    metadata:
      name: deconz-helm-values
      namespace: home-automation
    type: Opaque
