apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: deconz-helm-values
  namespace: home-automation
spec:
  encryptedData:
    values: AgAVXH4MhS7OSH6rKvjmVPR+2J51FCpxHZPPLWl0B0VpK5aDtQK1mutSppb6ZNYdqz2Jqz3e80ydPrq+wsPmfMb6Nfyy3dNWgbd56SDNOoavwN1DO5HwCEmHx98rk55MB9+/pemW9JRLKqseO1ofwL/5EKQYudOdiw9lJVIRkK7+McTwdwqCMsh33nTgs/naigHM3dfsa7Yp0NhAwkCfgTFAvAuHbutRleSOpwIi1qAm099wQKdfLCoSDT5Fr/jB6BhOgNtCt/4HeXkftoj3vd3Su35t6aMhBNwi6EDdgDoX1koaqx3mTt6kVDVNFHPQZkuwrs/WgUQ9Yet7XJQZDR1C78G2grm1vz/nlDerdjiMmKSCQGSuXjki9YkmN1KupHhooldDswVtoPvZsYhM2w0K9ZqqoQhVmT7fj0okaDZWrzQVcX8Htg5UhKtkimeRZXJvqWKBHPqd7wIHeQTbLFWoFZ0ZPspHLAusXLTHGT41tWhAviogsPOe8dNnu4Zx8HoFoe31/s8IX1CIPQzCUflpWLEX+gcinemF/iQIQIzqVJCmE7E4QGawXeDtlOO/LlydlNTlaccZOkTSCXeVzI9lTf0Y2luynNUW3v5Z5h7VcC/ecvy2xqk38r109h3CctEaaMiggmBtToJSLzo9heLUovEzobSzD2wxK5V3GAXN8ORyoAcUG5HgGdTGdZ7pzgZWtt4AiT9OWktrowyguqIexdIskaiPYCCLww==
  template:
    metadata:
      name: deconz-helm-values
      namespace: home-automation
    type: Opaque
