apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: deconz-helm-values
  namespace: home-automation
spec:
  encryptedData:
    values: AgB81sbG7Me0/6u+fLOXnKlc9G56lhmmoMSJSJJs/Z7XlPmqP+Qk2acUIhTmAk3oYGezWl+70+wcveVTf6QduZmLQyfN+0oPmAPqjtt/jXOKyagfNqmz0XQZA2gj1XGvGAYQhVhxOT+CYa4DtJwId1Sqv9y92QCxxnatmeTFUFNGxgu7lnCfo3LUuteSAhtvf7zu+cUnpyoV7aAjxU+gzXwClGeb5pIE55IZc21mh5Ah2nMZaIncu5dHa6YsO74kK+tUvM6fqXRsHFmu1fmok4doS80r2NPjQO/Mi3FsVfNUtq01WZmhCfHmJ+uX1akjlXQRtZBxcMAkNFVifGKqp6dS7ZUzdJX21163DQQpANw/zQj3Mcowy3MienvDtGv7WEIJ0Twn3YEbOrRDOkzDaXtbgoz/1z8BCNuM8SBNQQn6vjZsQYD62FdDK+QRU9Co1vAhGcINQD0cLnPGfNvnk1O7/KTUFc73cYENFks8sPsOk1ZZ17sWVdCITkQ8Ce6reyQdxlStIHO+Bd+U2JQTH2E95x9YvtsqMBBfKCngLGEEgx1eaxfriS8wx9tO3rdfrKeoUXw/Odsk2Cgf9hFHbZ7C504JHHHugoKmW/M0xESOED/mYkHkkU9jqANkHXzTm+rd5YXTglBD559HvknUZZWJBN5Q5gAsalHPKEFwp39raLfMXq1mrprrV5OHQDD1ZymQMXouh0zEdekSJRhw8VIkc1ZgBbe9xQNTMq4=
  template:
    metadata:
      name: deconz-helm-values
      namespace: home-automation
    type: Opaque
