apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: deconz-helm-values
  namespace: home-automation
spec:
  encryptedData:
    values: AgCGB2sXhIzKzv7DtJXKx5Un5qshYntDSlmIggi0O/aE3IYvLn0x9FIPIs4o8/yqMccuRZ8JAFmiSbR47eKiXFA4fZAn3KnOnsihNoKAgJ0PFx+IonKBd/nG99FTiuaVNzMukp2lh/ZpMM6ZFLVwklWxCTZH1+RDFsmZuksySS5hNiTP4Gfx3QfMBVYDIMnd2UrRZHXJKH6bsqi2LZdoUN+pFXx9shiSTU6c7/DObG1XKYM+n++xMJntXLvd8P6aa+ejic652FztjlsmKTW4LK86mIKkdJhuQ1H9QL4DHxq3tG69J4PTTDaCz2vs0v2mOwDUpBgAbMJfAP+d+UPnVDkGgyHxo1hYXpSFNYIWaa9Cbf3kxwIV654dvYIpH+Z1W1d5Fsk5ssvNnzOl1QHd5K2zY6KVo6uUQ2t9sg/99VqlFUMXQru4hHfvyaQvQ3GXZoLqO615Pz+VPb6nPfs8upZwdJqxempVL3vM3aG6c3eDZO33CQa0K+jCtp0yLIv9fzE07N5ooHKTpRI5bqLE9OdG372FmRUP0LemfuzPEDGEkc4pSBJpYvcOOvQpVsfy4esfD0c+Mu4Wf8U5hPfuLftQWiv9JTMuJO07zxH9HuK29+lJQJ4FeAW4CEr4ZPqtbw45vUS9A0Yn6+gn0N2ss5XU17ZEKRybCohIiBkoismZSqayh8fiaEUCeP24E2HXmPyfRpzU8Gs8zJubWz56wjK5xCRsnNERk64o
  template:
    metadata:
      name: deconz-helm-values
      namespace: home-automation
    type: Opaque
