apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: deconz-helm-values
  namespace: home-automation
spec:
  encryptedData:
    values: AgDCOfI0VdmPNSwHRstDfY249tZ2e7lUyrNCi/6orCJWwDEg1sTiB5ezTkwvoC0xMln7TgMfc1xuQLh8wk1bmxEH9MnuULZZ7WWQPXvC3w1/DQWlRnEZT7JsOmsd5n6oEcydR8vj6ya9Ha58WAicnXPtp+LB5Bi7W4xXJmcmWxfeo6aeGPrWAvyhZg9hh9YVZIxEqEene6m5EiO4s92kKelP1MfJ1p9KTOI0eWFHLUI1TakrMqPxgAohIbTxU30soXd0D/R2T1cgmTVw7MeiergSXsFgKYMDflLsNgYZQFVKRgQNq/a+NHq0kWIn2iwShs8ibBxlUlmUQbPH+cdF/h5c0Wy9n4EWCeyRKvCoJGf0bkW2dK/nNcKk/tv/VPyZAXwRPlaC0HPcxp8YGHrB4n+PiVldMfpYWr0PPmRvRWoAq/YSYAdWiUDOe4k2N1N02rvhq5l6MNdaaDuHR5uJKSYz78+w16uKLm1AMpwpxoOu0zQjA18gn2XjAIVgoymJWrZzbJ1xf3x3dQX/gUvaZERuqT9DBZCOD1r7eskFRS4xLKSOZVN8qfhBRqUutHn6oYGYqpuns1REnzOJQBfU+HMq70jkkeblIyvpg6SMlSPhuFxGk2Cm0S+ahht7NVMLBp4lipwS+jJeAl0hnJ9tfyzNLO7HFhxSUQeAyuxjslAndY+9PTM6fbB+p951iCDcjyE=
  template:
    metadata:
      name: deconz-helm-values
      namespace: home-automation
    type: Opaque
