apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: deconz-helm-values
  namespace: home-automation
spec:
  encryptedData:
    values: AgA/7QQd/L9hirAGs/XFCU6/wo3iCI2ds+4dRyGZOF6Zh7XGQDMvCKUdWOZTXEA5WIgW6Y0Qco7n00vLVg+1lVsfXgPqiOcMZK9+yVyqs7Ixlo9Z3Rwk7kgj/c3Mz4qSZQhkRuSfTKWHO+3Enh3Bz+ezHw9lZW2IZ3P7/VgAk5nEgm/E9ECoBEagrtNB95x20gSKBR4duBLvR+JXvdsr/1VVQ3ZAoEkKhqz53EXknf9w/s5qHZFJwJBI7FUca4zq8Pnv5BccDVg++HP4AOCW7+kf15HrjerNo4X6ehuQikPP1GrotXAZSWcWdcWvZOMDUKqUjTMO2GBMEbxWaLF1cnKJay8NGBlCyQ99hwztedCSZsLpsr0jufiJwoRXZlNIM5wSa3wJrM8kcPdvq9tk4LR95mAtfO819HTDWuCzSkzz4B27433Uod8C47f5LkiLbd8eaUj3GzDHsxJ1l2E/bgjWIuCWgZLpMJpcjFWXYXYvNDMMrGhfTfOc9nelMLRYrMzDYbfahWiGjI0lMqEXwo1zz6Sq+6868MRtxalEDPdIB0ZZfTUcloghIQhaZxm0pPzF1jtLfp7jlNtzGNt1JwHjAWn5i7U1X8GIgHHv78UlJ9A2W4ThAA4kavFvzR9/HfyHH8ADx3pDGhHigIO3YGf/9Lw5j3PS6N99ZKOISgM6vexqaiI8QjxkmpaWJTaQQq+bozGJnU0x2vd7LO9VajFhABhIvH+jO1Cu
  template:
    metadata:
      name: deconz-helm-values
      namespace: home-automation
    type: Opaque
