apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: deconz-helm-values
  namespace: home-automation
spec:
  encryptedData:
    values: AgDZFo4FMDBIMOv7xsKN2po7MitswJ8ZIoX6DZOe15ystVqwEFOaz/gIMqj4JdUtgJbX1xds79+kqykiffdHKkI8lfdDjqeLuHQckO8mEWU8MI4z+QDfeQb6RSQBMu1d72WCtof7wuBt8fdfczGc4XJlZgwv4Cti4FhnTXJ8ZoggWInTy+yxiYV1QZPAZtV938X2H493X6gXXtoXRxSONDzanDpPMAKm9QZ9Ac4XW547rsY54h+hT2qfqVj5ZVh6R/bBPQebSPE1GtQUlql8UZBZ4ODE1dCVs2bcM0Izj/jIN6ibOqsw0YxUu6nZUExeTmHD+rs6LHNygxWM6UgLAd2Ufei5lAj/AjeaoBh0OyvjGWL+0/i+sewmDZxGLX68PkfYUma/mHH4RcJbWfVTeIQJGaiOjYFbn7WZj4avOTJyT6viZwwihqNmgtk+BDQ0vh4T5IDNha14vLu0uEsMWSIARG5Dv+9PpCuoYWnACibRpGvb7H53x2AEzMC9D/1Ps4brAkv6Qd4TQ4hTUaRVPEbZrboz9qhvRxKknPlQFoYGYygr8dKbyj10sapH4mnTe1JftE7jOcIrQmvBwqabhA+Ki5N/OKvNwxiupr2cNsz/IEGKDWUK/pRuV8lXwa+pxQX6p0InV38PZDegKd0xLgCl1iexKUohYf3JCitc2wYhncoyOhpDahG6MSeRnH+0JkiayXv5/NFgykOOpzOnZGLR3uolATWpi3xUtA==
  template:
    metadata:
      name: deconz-helm-values
      namespace: home-automation
    type: Opaque
