apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: deconz-helm-values
  namespace: home-automation
spec:
  encryptedData:
    values: AgBK7k9IkGbVG1NExGUruhjeI13dJUWzAtWzrZzCaJQ+IROfifDezfqHm1Ag2fJ0USAFq0Sh6t/A88CJCpZ33HPiAKZsNFs3say3xibqmT9IgH3Ogrq20VTFYTaby+u+CEnPxZR2VwiEeHBde93DW3fvdJhanaR3fH6A1sqQOKztCcFz5U6pgO3YfiE0f3FAFAYmVeUTrNfPB3uf7kKfBWH3cpNa1+NZtxRco8vHYIO44+vA6Mjgyo1DoMOfUqIuYfa30Jb6So27fmrU++6lzzVXEHAZhuxFSEkCR7Nd24BDXrxSEnTYPQh04jeFzfQ4PpJHtcGjM/mytYcvCc5fdoltzLillONr7HRedFNLqHhysPVorsvxo2bQI7gMcvG33Y4jgiaW7bTIDnj7jwVRC9OOOV1FXomyRy7zojY+1e8VW/sFexszF8biGH8GRsJ0kWDJDZqI9nPV+kwjQ8bTXuCBw4ixzBSpx+ZP8MaKv5/k8D5LXksHY6bMDIqhC/KJSkoVjZVw2JVEfDYbR6SxHmrd8rKMFVbMbSFr3cJxi44D1wvqTY84alanDWAbkzCtHIWIsbV+M4cP97DHcZbvX4VyQkU/lnlQfNDKmOck40nkN2ojgwj7ubkdJncjr7Rr9SV2qG1tTMp0X7E2+V5jMQ6s5uRBFsMLqeq2vh8uwUp3BnOOgcVDJL+jg8XVIdOifHKbA3Ad157nTRGDighm+R5Wqi4YCztu3yIlKg==
  template:
    metadata:
      name: deconz-helm-values
      namespace: home-automation
    type: Opaque
