apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: deconz-helm-values
  namespace: home-automation
spec:
  encryptedData:
    values: AgCX43F4oos84jJ8hV6Iap6M3MTGDjbeGha4ai+k8KDir3WffTKswbWji70qt5oNcRg7BYoAcL7E7w/BauaPbO9XaFoiKN/TQZUWxAGOwUVHN4Qn6+VeUbCihcmhMfkQsbGL8sMnbHNT1kDXSEuh/entWuxq2WzWT47UiQSigAUU9uw7Bgj3yfaVHoanbpuEyYAHJ0U5+61XxWZaf+pdOH+cqDxAZT3p2amyz1PWydgFwmf8mZKqGWyovTxTp03gzR6VoazhUvIFC/i7ZUSnIVk3upItZ1vN4QEa8HjO57s+7Ro0zZN600ptMuMcdoWJmJA3Old6vRSBIY7x3RK5DD6wbmKR6avNxQxg1ynZCEjTDX9sc2yJIT9AHIJYvremtPKGP5BXjERH9zP3UMvC0H5WRuTKHCGtCyf5XwCiV+561amMUkjNAWGfBYHO4awzvfqVpVn2lBe2Zxska0xWGAwuPQIug1catcUQ6aAVqdH2/T49X24+01O6oX9X2unzbIMyl2+T2X441dLOfbKCFT5ruVxaIE70gn0JWCtmW1yqZVrbmPX1lr9v+zz8aiqsTEnaG7qrelBeqmbd3Rf0BFoN8ntWF5SEJ5F3CzCapie1bu6LlcthuQxyIehzj7anpRuzDxGg3173hbYt1aOtQmYk3pLOVTxpcWkFEYxFi8WCaxja67+p8z/HvhF9RUh4R8OLi8i0nkz/z+3QyOe0+v9sXpAlJ7svRequqQ==
  template:
    metadata:
      name: deconz-helm-values
      namespace: home-automation
    type: Opaque
