apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: deconz-helm-values
  namespace: home-automation
spec:
  encryptedData:
    values: AgB0f4fmGaGJefT6ZfoNzuwWWi9aU9qshh+pIjvgID5UNx8HG/pIh79RxcHxajfNrYOW7FksiivRkVfPM2TIL+RSy36bFa+Ny4XDzb1+KlS5UiYh/HVtBKZeah/R5DRpJfYFB8Wr/XJcYGOPrvDG/Bm70Ehbs8b8wss0pSPOxkmhPed+CFF5D1Rg/Gy0ooD0dpn4IXYsHfCzsDKXkreVOs2o/50A+3W4AznKMePdCEDKoP3QtUL1ibiepuwJ1H8wXdcGQb02rxpptnJHDPS8kNPYaW/gMcv+QmN10QnQOQu5duTt+9wfX2VAWf0B5heLXhvSX2Ll5M9Ih/urHxLh56HNC9Hx7auXduG9NWm53U5/yBOYQFHusBhrp3ZYlmVhn42QfT7LOMymrK7LzQuyrjcIpE++SSLXuJEQrSwk7nFaRQVRQpfh7jsW02QJKq3FfLmA74ITK83U624bGp+7TSFZP0K0AtcpENecr/V4gq9cn/a1nISW5M/P+w5doLZS0FtRxemZgPBVzKlIe+nOuh2yRISpixaX7cnmquS7DccKFXRMy8H4D+oc+ExYMIF5x3dQYsIC4R6TpMgTTA5xHVkqGwFuzSBCcprhkESnNJDukKLh8bNO+9H0b7943f9wQ1B/PSAzAg/ClqUawCdNQjlXLYlZtyC36D3alh6sS10F8LAZoYNYSRCrHrTI6KH+rG6i5Zfr0L0aO4KIw5FWl7Nixq3uhabNNQ0veg==
  template:
    metadata:
      name: deconz-helm-values
      namespace: home-automation
    type: Opaque
