---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: qbittorrent
  namespace: downloads
  annotations:
    fluxcd.io/ignore: "false"
    fluxcd.io/automated: "false"
spec:
  releaseName: qbittorrent
  chart:
    repository: https://k8s-charts.juggels.online
    name: qbittorrent
    version: 1.0.1
  values:
    image:
      repository: linuxserver/qbittorrent
      tag: "14.2.5.99202004250119-7015-2c65b79ubuntu18.04.1-ls86"

    podAnnotations:
      configmap.reloader.stakater.com/reload: "qbittorrent-openvpnconf"
      secret.reloader.stakater.com/reload: "qbittorrent-openvpnenv"

    config:
      timezone: "Europe/Amsterdam"
      uid: 1031
      gid: 100

    persistence:
      enabled: true

    extraVolumes:
      - name: nas-media
        persistentVolumeClaim:
          claimName: nfs-nas-media
        mountPath: "/data/nas-media"

    service:
      httpPort: 8080
      btPort: 24589

    ingress:
      enabled: true
      annotations:
        kubernetes.io/ingress.class: nginx
        cert-manager.io/cluster-issuer: bjws-lan-ca-issuer
        nginx.ingress.kubernetes.io/proxy-body-size: 25m

    resources:
      requests:
        memory: "256M"
      limits:
        memory: "1024M"

    probes:
      liveness:
        enabled: true
        initialDelaySeconds: 30
        failureThreshold: 5
        timeoutSeconds: 10
      readiness:
        enabled: true
        initialDelaySeconds: 30
        failureThreshold: 5
        timeoutSeconds: 10
      startup:
        enabled: true
        failureThreshold: 30
        periodSeconds: 10

    openvpn:
      enabled: true

      image:
        repository: dperson/openvpn-client
        tag: latest
        pullPolicy: Always

      env:
        FIREWALL: "on"
        ROUTE_1: "172.17.0.0/16"
        VPNPORT_1: "24589"

      externalDns: true

      livenessProbe:
        exec:
          command:
            - sh
            - -c
            - if [ $(curl -s https://am.i.mullvad.net/country) == "Belgium" ]; then exit 0; else exit $?; fi
        initialDelaySeconds: 30
        periodSeconds: 60
        failureThreshold: 1

  valuesFrom:
    - secretKeyRef:
        name: qbittorrent-helm-values
        key: values
