---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: qbittorrent
  namespace: downloads
  annotations:
    fluxcd.io/ignore: "false"
    fluxcd.io/automated: "false"
spec:
  releaseName: qbittorrent
  chart:
    repository: https://k8s-charts.juggels.online
    name: qbittorrent
    version: 1.0.1

  valuesFrom:
    - secretKeyRef:
        name: qbittorrent-helm-values
        key: values.yaml
