---
version: '2'

tasks:
  flux-sync:
    desc: Force cluster to run flux
    silent: true
    cmds:
      - fluxctl --k8s-fwd-ns=system-flux --k8s-fwd-labels="app=flux,release=flux" sync

  render-templates:
    desc: Render *.tmpl template files to actual files
    silent: true
    cmds:
      - ./.github/scripts/render_templates.sh

  lint-scripts:
    desc: Lint all script files in the repo
    silent: true
    cmds:
      - ./.github/scripts/lint_scripts.sh

  lint-yaml:
    desc: Lint all yaml files in the repo
    silent: true
    cmds:
      - ./.github/scripts/lint_yaml.sh
