---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: echo-server
  namespace: system-ingress
  annotations:
    fluxcd.io/ignore: "false"
    fluxcd.io/automated: "false"
spec:
  releaseName: echo-server
  chart:
    repository: https://ealenn.github.io/charts
    name: echo-server
    version: 0.3.0
  values:
    image:
      repository: ealen/echo-server
      tag: 0.4.3

  valuesFrom:
    - secretKeyRef:
        name: echo-server-helm-values
        key: values.yaml
