---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: loki
  namespace: system-monitoring
  annotations:
    fluxcd.io/ignore: "false"
    fluxcd.io/automated: "false"
spec:
  releaseName: loki
  chart:
    repository: https://grafana.github.io/loki/charts
    name: loki-stack
    version: 0.39.0
  values:
    loki:
      config:
        table_manager:
          retention_deletes_enabled: true
          retention_period: 672h
      persistence:
        enabled: true
        size: 20Gi
      serviceMonitor:
        enabled: true
    promtail:
      serviceMonitor:
        enabled: true
      extraScrapeConfigs:
        - job_name: syslog
          syslog:
            listen_address: 0.0.0.0:1514
            idle_timeout: 60s
            label_structured_data: yes
            labels:
              job: "syslog"
          relabel_configs:
            - source_labels: ['__syslog_message_hostname']
              target_label: 'host'
      syslogService:
        enabled: true
        type: LoadBalancer
        port: 1514
        loadBalancerIP: 192.168.26.7
