---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: radarr
  namespace: downloads
  annotations:
    fluxcd.io/ignore: "false"
    fluxcd.io/automated: "false"
spec:
  releaseName: radarr
  chart:
    repository: https://k8s-at-home.com/charts/
    name: radarr
    version: 6.0.0
  values:
    radarr:
      podAnnotations:
        replicas-max: "1"

      image:
        organization: linuxserver
        repository: radarr
        tag: "3.0.0.3624-ls21"

      env:
        TZ: "Europe/Amsterdam"
        PUID: "1031"
        PGID: "100"

      persistence:
        type: statefulset
        config:
          enabled: true
          existingClaim: config-radarr-0
        media:
          enabled: false

      additionalVolumes:
        - name: nas-media
          persistentVolumeClaim:
            claimName: nfs-nas-media

      additionalVolumeMounts:
        - name: nas-media
          mountPath: "/data/nas-media"

      ingress:
        enabled: true
        annotations:
          kubernetes.io/ingress.class: nginx
          cert-manager.io/cluster-issuer: bjws-lan-ca-issuer

      resources:
        requests:
          memory: "256M"
        limits:
          memory: "512M"

  valuesFrom:
    - secretKeyRef:
        name: radarr-helm-values
        key: values
