---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: radarr
  namespace: downloads
  annotations:
    fluxcd.io/ignore: "false"
    fluxcd.io/automated: "false"
spec:
  releaseName: radarr
  chart:
    repository: https://k8s-at-home.com/charts/
    name: radarr
    version: 6.0.0

  valuesFrom:
  - secretKeyRef:
      name: radarr-helm-values
      key: values.yaml
