---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: radarr
  namespace: downloads
  annotations:
    fluxcd.io/ignore: "false"
    fluxcd.io/automated: "false"
spec:
  releaseName: radarr
  chart:
    repository: https://k8s-charts.juggels.online
    name: radarr
    version: 1.0.0
  values:
    image:
      repository: linuxserver/radarr
      tag: "v0.2.0.1504-ls74"

    config:
      timezone: "Europe/Amsterdam"
      uid: 1031
      gid: 100

    persistence:
      enabled: true

    extraVolumes:
      - name: nas-media
        persistentVolumeClaim:
          claimName: nfs-nas-media
        mountPath: "/data/nas-media"

    ingress:
      enabled: true
      annotations:
        kubernetes.io/ingress.class: nginx
        cert-manager.io/cluster-issuer: bjws-lan-ca-issuer

    resources:
      requests:
        memory: "256M"
      limits:
        memory: "512M"

    probes:
      liveness:
        initialDelaySeconds: 0
      readiness:
        initialDelaySeconds: 0
      startup:
        enabled: true

  valuesFrom:
    - secretKeyRef:
        name: radarr-helm-values
        key: values
