---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: radarr-helm-values
  namespace: downloads
spec:
  encryptedData:
    values: AgBlcGjBKt0L0QHYzpfyoMnI28KlyNwjjpGp5lKEGVyvK4UHDxr4lKZobVzQ6znHfgjdWrelCntXG3R1rMCVFVKtdxt4gZS8xSfH4kzafNUz4NcBDOBU/NNgXWIzXkeVn5+I8ADQ671a+QirC5P+xf5GtjPxUOpEbVyM+9wMv9ghd5WEpWtd2k3LGhOTbchsNg3N87jrCyLcxQtN9HV4Q2OQi2jszl7olFkMpaQwiihIJ3Wft4aLL7ur5gpKFlq3fTX+Wceu6WrRPbeNEL9VbgFRf4DorNjRz7R570HnIYjV1K0BJtzVFOwMWj82KORWj0wUEMiYkZaTxUqq9HlF6z8GJdHZUKqrVSnvuVEwNMX2poLyP0tpW5lsi0Rw3bAldQXpgJdN7/+a7mj/cMyeH3TKNOKf8zdvqA5nXO8jWqppbe+0zRrWqXlhPBaU5hY1LlKGtZT0EW8ksT17cQH+r1dbm2sLrz6JMKeMNmIAp32OhpPQIk64qstjhNvg48x813XfkX6XkEvlKLbcVMFGcLVmkpZmMHKqPCcfF6bC6h/xpMxe5ICyBQPMDYDftU8+/riZxBP+wYLAVRbn9D8u+zTHXwqLqf0JYNMHjDHnLhWWhZaySLPcvWQ87Q9ajSEdnZMJ8ujzJZ2zFh/j7EOSQoBT41VDiHfCCcY9jWbKZ3JKka6DesvkUt8VFROVGXxEfqBfHTJhGrr8+b4OKS3x7JSY+AiysUUGTcYj5uPw7afUbTvRR809pGATy+9sahlsZGlWH76vIH0QJZJVYMZXO35HIWZDMkoIzFTjkxv41d2DKaEMfLKRnRzMwqovvllWkYni+dVwWJnMWK67F62F11PmvCpghJ+25X06p9fwluVt9JqmTujW55TUvxOBbLqf9NlIZJ27t/+dhfh4KQcTMtwlHtVhr+JoOSEkkQw3Chg=
  template:
    metadata:
      name: radarr-helm-values
      namespace: downloads
    type: Opaque
