---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mosquitto
  namespace: home-network
  labels:
    app: mosquitto
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: mosquitto
  template:
    metadata:
      labels:
        app: mosquitto
      annotations:
        backup.velero.io/backup-volumes: mosquitto-data
    spec:
      containers:
        - name: mosquitto
          image: "eclipse-mosquitto:1.6.10"
          imagePullPolicy: IfNotPresent
          ports:
            - name: mqtt
              containerPort: 1883
              protocol: TCP
            - name: websocket
              containerPort: 9001
              protocol: TCP
          volumeMounts:
            - name: mosquitto-config
              mountPath: /mosquitto/config/mosquitto.conf
              subPath: mosquitto.conf
              readOnly: true
            - name: mosquitto-secrets
              mountPath: /mosquitto/config/mosquitto_passwd
              subPath: mosquitto_passwd
              readOnly: true
            - name: mosquitto-secrets
              mountPath: /mosquitto/config/mosquitto_acl
              subPath: mosquitto_acl
              readOnly: true
            - name: mosquitto-data
              mountPath: /mosquitto/data
          resources:
            requests:
              memory: "64M"
            limits:
              memory: "128M"
      volumes:
        - name: mosquitto-config
          configMap:
            name: mosquitto-config
        - name: mosquitto-secrets
          secret:
            secretName: mosquitto-secrets
        - name: mosquitto-data
          persistentVolumeClaim:
            claimName: mosquitto-data
