---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: mosquitto-data
  namespace: home-network
  labels:
    app: mosquitto
spec:
  accessModes:
  - "ReadWriteOnce"
  resources:
    requests:
      storage: 1Gi
  storageClassName: longhorn-static
  volumeMode: Filesystem
  volumeName: pvc-04965d3d-4153-4637-bf78-4e13f2abfe86
