---
apiVersion: actions.summerwind.dev/v1alpha1
kind: RunnerDeployment
metadata:
  name: runnerdeployment-gitops
  namespace: actions-runner-system
spec:
  replicas: 1
  minReplicas: 1
  maxReplicas: 3
  template:
    spec:
      repository: bjw-s/k8s-gitops
      image: onedr0p/actions-runnner:latest
      env: []
