---
apiVersion: actions.summerwind.dev/v1alpha1
kind: RunnerDeployment
metadata:
  name: runnerdeployment-gitops
  namespace: actions-runner-system
spec:
  minReplicas: 1
  maxReplicas: 3
  template:
    spec:
      repository: bjw-s/k8s-gitops
      image: onedr0p/actions-runnner:latest
      env: []
---
apiVersion: actions.summerwind.dev/v1alpha1
kind: HorizontalRunnerAutoscaler
metadata:
  name: runnerdeployment-gitops-autoscaler
  namespace: actions-runner-system
spec:
  scaleTargetRef:
    name: runnerdeployment-gitops
  minReplicas: 1
  maxReplicas: 3
  metrics:
    - type: TotalNumberOfQueuedAndInProgressWorkflowRuns
      repositoryNames:
        - bjw-s/k8s-gitops
