---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: node-red
  namespace: selfhosted
  annotations:
    fluxcd.io/ignore: "false"
    fluxcd.io/automated: "false"
spec:
  releaseName: node-red
  chart:
    repository: https://billimek.com/billimek-charts/
    name: node-red
    version: 2.0.2
  values:
    image:
      repository: nodered/node-red
      tag: 1.1.3

    enableProjects: "true"
    timezone: "Europe/Amsterdam"

    persistence:
      enabled: true
      size: 1Gi

    resources:
      requests:
        memory: "256M"
      limits:
        memory: "512M"

  valuesFrom:
    - secretKeyRef:
        name: node-red-helm-values
        key: values
