---
apiVersion: v1
kind: ConfigMap
metadata:
  name: nut-upsd-study

data:
  ups.conf: |
    maxretry = 3

    [ups]
      driver = usbhid-ups
      port = auto
      desc = "APC Back-UPS BX950U-GR"
      serial = 4B1931P01757

  upsd.conf: |
    LISTEN 0.0.0.0
