apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
    app: nut-upsd-study
  name: nut-upsd-study
  namespace: home-network
spec:
  selector:
    matchLabels:
      app: nut-upsd-study
  endpoints:
      - port: http-metrics
        interval: 1m
        scrapeTimeout: 30s
