---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: jackett
  namespace: downloads
  annotations:
    fluxcd.io/ignore: "false"
    fluxcd.io/automated: "true"
    filter.fluxcd.io/chart-image: 'regexp:^v0\.16\.[0-9]+-ls18$'
spec:
  releaseName: jackett
  chart:
    repository: https://k8s-at-home.com/charts/
    name: jackett
    version: 4.0.1

  values:
    jackett:
      image:
        organization: linuxserver
        repository: jackett
        tag: "v0.16.1269-ls18"

  valuesFrom:
  - secretKeyRef:
      name: jackett-helm-values
      key: values.yaml
