---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: sealed-secrets
  namespace: system
  annotations:
    fluxcd.io/ignore: "false"
    fluxcd.io/automated: "false"
spec:
  releaseName: sealed-secrets
  chart:
    repository: https://kubernetes-charts.storage.googleapis.com/
    name: sealed-secrets
    version: 1.10.3
  valuesFrom:
    - externalSourceRef:
        url: https://raw.githubusercontent.com/bjw-s/k8s-gitops/master/deployments/system/sealed-secrets/values.yaml
