---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: plex
  namespace: media
  annotations:
    fluxcd.io/ignore: "false"
    fluxcd.io/automated: "false"
spec:
  releaseName: plex
  rollback:
    enable: false
  chart:
    repository: https://billimek.com/billimek-charts/
    name: plex
    version: 1.7.2

  values:
    image:
      repository: plexinc/pms-docker
      tag: plexpass
      pullPolicy: IfNotPresent

  valuesFrom:
    - secretKeyRef:
        name: plex-helm-values
        key: values.yaml
