apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
stringData:
    CLUSTER_SECRET_CPGO_R2_ENDPOINT: ENC[AES256_GCM,data:0oYGGnXOK1EWaFrhxpODPAZsD5RS9+RL6cHAPTEMw8xq5f0tzbhvOnKNUw/hNZBPtDYQymLsz4P8DdOf5/0e3kMemYw=,iv:aQubf/2gJzwnwq0uAqmWUikk9RayNFYAlgYo/CkTjEE=,tag:qW7f9sG1/+riLOqDmf44Rw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1uk0y2ahfavgsgqvrtg5a22w5gytpdmjuatxtcw6kntmxhlcgreesuwzw5s
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBvaHZqUnp4bzk2NytmTHVD
            eE9LZ0MxNXJYd1luZk5lRTAwN25heXBSUndJCnRyZDVxdDhlUEJwS1plakpEeGly
            VHJDc2FmOVFrQ3ArTTdpZ2RLUm44VVEKLS0tIHI5ZjY5U0h3TzJIVXk2bW1oNGpR
            MlJBc1dFby91Mmh0TUlMWkpPQS9kdGMKRWZHnaeVLAXUnaQ9q0Si921yjyth9eHA
            kNVxiir6Kdv04xM4KMCTecrz8wjNLkqWXmkYSxaIXXm15plIymRkuA==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1hawjtl6fm5czl8cun0ve7jvsmpqpn3qlxl2lnx7ndt7682tmva2qz3drfe
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBidE9HL21Zd2x1VjdYcHJV
            bCsvc2piT28xMFJHYU5EQmRNajZWazdMeG0wCkZ4SmN2Z3cvN2orMkhINDlwT1BU
            eUFpbDUxV2NkK1VtSk1IVERaVGNldmcKLS0tIEhYamlIWnZXMFdHRWRnYTdHQ2tX
            Q2REVE1uQWJBQ0M2Rm1DU09NV0FyRlkKYyxHC15MqWAcQlwwDN6kRZ2fTFw83lmh
            Q5nCLJYHlfdux3miXFwGhkXv8SuCoDjFvCNvi/ZQDPPFKMQNRDs2Pg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-07-23T17:26:00Z"
    mac: ENC[AES256_GCM,data:LZV42reEykIU13qZZlDN+KFeyF73HhONPFCCy+wbZss4KfAOd+58RIvt0gvK+ibPWEErlSwXA3IrygSZJp4UpKsNDkICFIKYAsG4dAAr/0nyeKeze63v1pRLjNJR7LwRpdC92RGF6d4P6rIktgrE8DiQLeWEU39xwdm20DDU1Bw=,iv:8wfeIHPtKoAmGJbIcY41hZlb1kaLUaiA/pecwOr9RJ0=,tag:zKPa5w2fMPSUXgFFd/ubpQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
