---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: longhorn-helm-values
  namespace: longhorn-system
spec:
  encryptedData:
    values: AgCvvAak2YIyPDm+z2r8HyorFM5BR5U4X18LlYJrU0N1uzpEUjsZv5nuLLA1GsZc2eVRt1hRoM8QQsiIYU0wUrMYc1sNZNMGYjzG78MUNjPqW8HxlveYHViFWEWRXpKxzzNnVe9aaHPYanB/BzDGzHWU8k5MpXhVPJtGyktz+2+lkOonS/yV4drdBT+QnEo9Fi5TQyy2NZQRQAhLlDPtD8NZa105m/1W+hthOnXBtW3TSnVvxINDMGQn8M97IAnFzsHGna+mekEFjZM2tdaNmBX5JHQESUSCakk/pSIBGNi+195sr6+RdgknHKtXpnl01MPTaWpoBe0W8X7wbF3sSsaxHz7ia0j2/YxEJErqmdzM1eWZX5NqjmlBIUZbkrFMydRar076IIsmTqyBPK9ilo6fIW3gA5zPS1gxP/txSmgRniayssresaiCVpTwKfpLpnnkJN3JNIrhOxX5yQpm/naho87t0R2DbxlWukQFu3mNtUJwU3VpKXJxOy1DBLkBWZpG9JmwDFs0maLW4IBFBnPd/9vuWpirxEIRf77yg2j04HWINtr2fTWLPWP4StXOAHyODy/5VLHBk4oU81thn5knJ5HUzjVFIwWmuEcKBoQtnujqdKq8U56WJJ5OL1uxVkkUlEpGcVumwLuvw9bsfjDmo3hkZcRmV2GQEXNAJ8xaldpRhLN2DqcVVKt4QwJZ8/WFmGnsbx9+IhZPs2Xal7YjNW39LZGB+vZq7mZEcss55vxlYRrGhrTa6f28wnBroKBUOGvGV+hPTTyQNNTSUQ80dxMb73+zU/iDTLThKzaeXHp7BNONkz4SyqSbYIB+nMBPCMi9zp0VV1oLxkNvsm5bSaEDrSo0xaX3+nDJ33eTkQTHO18H1VhvlKbe1LYtIn6zlo3npEgDP+/7B48i79cUX+GBvhg9ZDDVkR1NhOC7cGXlLSE8sI6sW8bZVkJAiBeD7VE+9vnxaBtY46cUIb3rfD4YeA5fhkAYQq8bgxGtOOaqhBxgLfvMjKSdvetHEO730hIifA5YgnLeStqCCC/eux3HgwPXgCnZuTr4dXbyYxCVa3rWPjxd5+7r8NdUG7Cm/AMY1cvk8UFAxFLAtpKTuoqPBxphvFyvl13sz428AYq0EfZTvLBuopdr3ibgmzQu5utMU+MxPUDloDXBlWaRjLN4XD+Asxa5oiSycZ2QnpJNmE8koaOPrF1e2VXYseGY/b0CuPAx2cIaJOPuX2kQwwRR4R/HK3JEVP37RQ==
  template:
    metadata:
      name: longhorn-helm-values
      namespace: longhorn-system
    type: Opaque
