---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: longhorn-singlereplica
allowVolumeExpansion: true
parameters:
  baseImage: ""
  fromBackup: ""
  numberOfReplicas: "1"
  staleReplicaTimeout: "30"
  recurringJobs: '[{"name":"backup", "task":"backup", "cron":"0 */12 * * *", "retain":14}]'
provisioner: driver.longhorn.io
reclaimPolicy: Delete
volumeBindingMode: Immediate
