allowVolumeExpansion: true
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: longhorn-default
  annotations:
    storageclass.kubernetes.io/is-default-class: "true"
parameters:
  baseImage: ""
  fromBackup: ""
  numberOfReplicas: "3"
  staleReplicaTimeout: "30"
  recurringJobs: '[{"name":"backup", "task":"backup", "cron":"0 */12 * * *", "retain":1}]'
provisioner: driver.longhorn.io
reclaimPolicy: Delete
volumeBindingMode: Immediate
