---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: calibre-web-helm-values
  namespace: media
spec:
  encryptedData:
    values: AgDMJH6jsUaxzzHKWDo2ghDGV8H6MBvGzX5LGaOW+t6icM3GKcOBTFN3oEmHDLHG/VUORU2FI6ki38QUCMqPl5WjgmsW86PQ0fkCld/r7qYKQ0ExYzNXVS1gpzUCq8KZWvgJq64TVJXe/holbTgatrEzi0Ey5FuW2YTuaqCc7tSthUX/EeNP7I4M40q0zwCozVrZrdoOFpZI4b/xcJ8PX3R15z7frQp9yxfOylVf3t5ySsag9MdIX0ERvK8pwewrTxwJQx6bOmx5aDdDIyKhifGpqSWdhB7ZAa9QzCUBwliX03Hze2ntLj6+1M0J3lycitv+SvYYj/haNmRB1uJ5UVlwq4gy5BGj+ohOxf1Da0hpBoi6GZ503/hYwm8xeg6PC4lM9rf2hhnnR8uQSdu03z78dKHN2RCuvhqtSEplpWkcSN7AyTFMtnevdmSFpdrkt5jnJB38ZwkgSci+VOyh1s9XJ8hMkR2R/GWKZpbfqyExDDfF9BMshh34CwsVFAg2wikK0bIntDIdki8NyjJX5sPq+dGiEJpvzXfS+GFlqUbxgZ32tMJZVRK+CpuvgEH+YyII6pYfgms01ZFreIB/Kf6ERl6K1014EIdi9Vg5EW35eIuza8p8GhrkyilbfzQdh8uKf6/XIx/mMA0fqDZ/CEADv5pclp+xGWGDz5l+06nL2o/9eEXpLc5U7FxUkYHxd067zeBT+7e4ilLOUVHDHPpiMQJQDw4HTc3gFib/O6lZLpgeSj/z3nLuc61HBYw8icMng7XfhpB76GHymaHQPjpJjxYdp+GafyvAmMrXVLWzfNJLrj8DachMjN8CsjBV3LDYewEGU2zRhYPy9OwTPBwgUgUnKlQyMYsjWPqVcIZoAPHuCwroQyu5
  template:
    metadata:
      name: calibre-web-helm-values
      namespace: media
    type: Opaque
