---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: controller-manager
  namespace: actions-runner-system
spec:
  encryptedData:
    github_token: AgBnbTTqp+HVYWYs5jrzdt4GF+1ZWyRmFoVpSS2H5fDdtiIoWkpoQ63PwCqSrit4TrOaU5p7EBFnnzywwIWBPcrlgn67+dokgcFDGA50bQ+W8sHu1kbkG89eImAU4bq4fnSAdve2iFn9IHU/hVP0KC9xQljJZgrkEqLeZgxwmxgSqpSmQMaXE+6h6fSNfwkB5X2E5GghJQQq69udp/tNIZEisSZMOkfxRZv83oUitPmIj8x5mFOG+EsO7oSIfNXUfMR+I7+sQBRsnnKBoREMjMHV/pYkFkLDxZaYbE8Ke8OBr7X85NxhKLSudBou+tpIGBPmT1huJYuBaiShns2MweFI/YH7/TtlXpGKLcgaSsl2KwxRCjajmf4kAvuhyQx4jvRspBo5hBou17/ugubw1r8cFuttPnOM84fPQM4aYsNb9sejQKM45V8bxJ4b5L9m/8zbmwoxiqCjVjI13oZVOfctk6/JuO2cEyxUg5E4kb7CT6BTXYzzOPd2TcLhZTuisRK+iDFck6z1mUgI+rnIWUSgZvjr7teTqSZmEL/63RShs3157sJViWvl9mXLydVzPn09Pia9Lnq/iYfAXth9siP+BoP/gDWvvnBshaTO8aZHfUEkmbs/hCz3iRaU4iQKq8WLCGRvcWWeBMtcMIWZwQDa1iUPrD6Trdshtb+Q1j1/4CPCknP98d2L7Y9/FlZSXv8a8h16mnuCoq2RH9OMVza37gO5kwFTJNfEF4/sPR1Go/0NIslxwPRQ
  template:
    metadata:
      name: controller-manager
      namespace: actions-runner-system
    type: Opaque
