---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: controller-manager
  namespace: actions-runner-system
spec:
  encryptedData:
    github_token: AgDSjUaQ21bh6Wc6nwOvu3vtkEqvORVBClifEZgDRmcVJElA/0gFtAbAST/NUEgIXasKBYBH+dS8Vumjy29CkPZKFzsnz6hYBJk79eh38yGex3EaolIJsYmz2nalVKRpu9zldfu+sGwYR4DB+qD5QiGcWWfet0+n3wGh1eOmxr49Wx2mdeLAtro3BANNOpYFOqjWF54USDQxV1srjNrkXbxt2O+b68LIdHSgH7bqweOm+rmcazocH2Y3ZHtYaEjMj8cmtNUU61Qik2t8GVWnqDGIgllbiJ78lmrd9tcdY3p+tUbutrYA0yNfxwlZq/K6PFlutBt5jiFcvccTur6gQu9gQRHHp776H2f+ZtmCLLQcuaG/fepa81qBfZMfgTJAkkug5DUZqNxuFGFyxpMPPHmmkI+gAlJpHNkopWHyc5TTdGkvsHW2nk81RpG1tKhjdUB+5fpl14bYnRPdWj9cyGXX5X0pe203RDHfr8lG/oQ1O8+prpsglMIUoG+/ZlK6zfPSBXoZawB81PY152LSUFEzLjlMS6rYZgyC94WMN50LcDqdEQdXiXatUAb279WqbTdDzFM5rFCZKnr+OnsfJ7IXJLijJWGO8LBzN3N0j6RS9bp1ASNNlwwwgf+3ij/T76A0bqez9W4osacgT9AlTVBH9GWlnzJ9BeLQKlVxV6Hw+CigX/Kr1PxnIpXSETMlCpyCPEERT5zCI4YxIPPFqwTwPtiQfNDxSWLFsihsPliJ4Qm3oVpCows/
  template:
    metadata:
      name: controller-manager
      namespace: actions-runner-system
    type: Opaque
