---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: controller-manager
  namespace: actions-runner-system
spec:
  encryptedData:
    github_token: AgC0V4EA7AxC+B/th8tpB488scJyHE0E51ePJtgQ0fiRAbZ7XbAI4Oie6kbwZTToGoot/pTWSg6Cm3QjzrLKrw5Ls3HlwPBLn1jsFHMP7OW02w0DY1WS7mvG2wdvuboBUOcyRoPEqkT9K0B7G/af/NhNJs8BoUC+VzCN2R0lrSsw0XpSOgyB04NHJtCydggw0qex4aNud+XocMHO9LFoxe7nzjA33M5VFV4L6XY704YMgYwHRgUxvFmzg+XsxzNB2oxHDbUd6BeQvaKithSgocoq0GEigRBMkTDNUVARS180Yjb6Q+VcffKA2//hQ/UI9ICl/NYj0DpEeGOQ6/yOLu4raXP8ZBlSbcyaLon7OJ3Wp8QvVYhJqCkIX84cQjbt6BZ/yjN2k6zEk/xqHBzHVVAIfhJFAi3oH3pwPvBzG1ljXJfDbDjyaZWUBmwGUW/tBdj+hFaPkVnARZn8QfzSf221xAtKjEJU5+RX7EZSMP6Lw8LTgScnQSkArmZCDqAfjsEbYWj+JjfRGMQtlKUc1SxtuZFbHxgJyN/CZwZGb7PMowAfGtgIqVGTD7/TNXBivSKzRdh5QLJ3npiO78j98cnLNQTDmtg/bVLCqxl4/CnBesjZBAY4ryWS80Huly29bpWqUlOTkSQ2KOC9Cmy/C65C9wPC5apz5qcJ81UXHjslWC63JWdzYDB7aL71DJmeHqYHJJm5/fHX+yVt40gP5PTQCnAWTR9Qpyha5T/YMm72IGUjQ2GqDl8w
  template:
    metadata:
      name: controller-manager
      namespace: actions-runner-system
    type: Opaque
