---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: controller-manager
  namespace: actions-runner-system
spec:
  encryptedData:
    github_token: AgClvPyppN04fTrHGxOM4LMQK9fQ8vT+1JGbL7M9cOfpSgFkHFsvBPDx29Ei8rYQ9tIdlhWLBRZUh4jTb0EMiCDjehqDbL2K8FW9bbQ6XsxFmsnnOu0jxfiuTSnNs8APHmtjOP/46P9JXd8v93DWBQ4ccNmWV6SyL01/LOLY6yg7T7tIEZT6vpBzEx6sj9EjK6bzQe+bOnnO+ps6f7NrwYCb9mivnL1T0DNgnY5RFTfSDUZfVIoh/udjsjcUI+aXJVdVQnOaIDo90jCDUgww5jQWAKqHCr7nfEbzkLJZNgRppmEiYIfgW67Zmix4q1yV6bKE9l8kPB8VF7vLMvpi9zQw+ynVgpOmE6CqohsWK4ee/Knm0xWq8KlpXdTbFTZXCcNBQtJz0aApKmmWONLGOVsFFzJpMPLE6ZtNyy2jIbs4JjSWuQLOmHcZjuVzBwegGniOoyhLqzhwxA2LhZL8Yw0jwmbTOj/G3Mqm+5XQRc3k7RwfmGu2CZz6p64WucvCmEDoiEGm/D4kgloxxvOmd996s/zt4+bEZWJJAO91bQacZOngNYgmsUoX8E9csHtc6WogoMjUNf04ElWGEkur4mgN3kBWkTiZcggVybXtq87hISdUeLVK4Brsc6U0z8oukCA1wYir2abwStnX8JX0PSAbbUBrGwvBYq6eqGALOY5IhmVqLa2fA3OXjQF/kxozaWBepPPlctVp+f/KHEoVmoD+raSo4txWEtj+v1vLuMoanFSu7ll/xbP3
  template:
    metadata:
      name: controller-manager
      namespace: actions-runner-system
    type: Opaque
