---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: mailbackup
spec:
  schedule: "0 2 * * *"
  concurrencyPolicy: Forbid
  jobTemplate:
    spec:
      template:
        spec:
          automountServiceAccountToken: false

          securityContext:
            runAsUser: 65534
            runAsGroup: 65534
            fsGroup: 65534
            fsGroupChangePolicy: "OnRootMismatch"
            supplementalGroups:
              - 65542 # gladius:external-services

          containers:
            - name: mailbackup
              image: ghcr.io/bjw-s/getmail:6.18.14@sha256:9d7ca49afb1d60a8febcc99cba697b79985f67a559c66dc30f216ba05e3f4773
              imagePullPolicy: IfNotPresent
              command:
                - "/scripts/mailbackup.sh"
              volumeMounts:
                - name: mailbackup-script
                  mountPath: /scripts/mailbackup.sh
                  subPath: mailbackup.sh
                  readOnly: true
                - name: secrets
                  mountPath: /config
                  readOnly: true
                - mountPath: /data/nas-backup
                  name: mailbackup

          restartPolicy: OnFailure

          volumes:
            - name: mailbackup-script
              projected:
                defaultMode: 0775
                sources:
                  - configMap:
                      name: mailbackup
                      items:
                        - key: mailbackup.sh
                          path: mailbackup.sh
            - name: secrets
              secret:
                secretName: mailbackup-secrets
            - name: mailbackup
              nfs:
                server: "gladius.bjw-s.casa"
                path: /tank/Backup
