---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: series-cleanup-data
  namespace: media
spec:
  storageClassName: longhorn-singlereplica
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Mi
