apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: external-dns-helm-values
  namespace: system-ingress
spec:
  encryptedData:
    values: AgAC3asfuE066jdtHC2+f9MfjiEr/xMaoMg+pl2VbUHe7AHu1MeVSkpUJzKlvBMx7PL9ZC1IUz1iM+vYep3w5HoMZsNEBosM/NKxzNWzciAfJgGQOPi08MMpf5WCfh4aowyw6M8WHVI1oFiT1UhKO7MTYZ/51MbYldCP1HAsw6IPSP/zyxicAR5CT8Cd+MgBoA/tc4KRXapNkyTQbkOPj8AOev86LzZvoZvuMMd6LEhY3lZysCRlR2uk42MoRXlD9vfrRig7nBzGnWyjbl0qdbHuR3XPyYnBc88kZRrVUogBSClVThvTnS11srWeKMmkTXxwF7NhZ0vuy7X8paIkeptkcnxOO4F/fUCaAeU/kKQcbqGZYUadYXT5jU0uauYYZPa56C78F8Nhuz3wRNwpfq6Iqxl3fsG8PCc1I9CCQjnnSuVMGXy1iS625jlPjE1PR358y7Ro9ODpJ+pL8u8+/XVS2ir2DeghIFbdW0HUg2nzcT3r3jXMZdixkLHmRRbXARlbCwsR4hERzT9zf7tRPqh64KUt33WU68UEUG4i/OeyyzMhSENCn4YC0BbvF8Y2ZTwv9EbZtWkOztltRLM/Ul7h7fAaN/Ska7riSN1x81DRZpeRuVuh48zEUaYEnWrALCZDu53CIq9yBJvoOqXOOniYooGCVSVoOexudWE4dNbiAAFYCPCM7d9k/yBcrV3DDMUttcMPQhGErbw4Zi6fntV1AATASkonbwPfigGxtkvhpv/Dsw29TLZI8sjasqvzFr/3D+L5Co0wyjiIprQC8qOQYq7L81b5RTh3YSG4SKcO6qC1jfhUGsf8xh0UYRjNui0Hj2GV44jSaIR6qk8ExvfyjH1/3kwaTZqiUJzIDw==
  template:
    metadata:
      name: external-dns-helm-values
      namespace: system-ingress
    type: Opaque
