apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: external-dns-helm-values
  namespace: system-ingress
spec:
  encryptedData:
    values: AgAf4KLmKu2HJ1NTF2guncl8ElLwUuffZq/pxpH8pQM9Ps8GFR0bOyTL6OKOjh8PW2yeX0iYS3qKi6rYDOSJ7qeZoy2Sqmwrd/UWJmtAPRX/ioIRChsGpxlMuUD0TKkCcC2muG5XGzyerycGm2Z27LKnX53Ot2hL+osu9dejA9Udgvav51aI/GAA1P8oLqA98sDGd8xH0U92/E9IZAtfkhhtPWqPjVco65jkjfAScqY27uWMj4f/jehwQdCTlxe9cHgIg5czFE8gIG0Q4lDy9YypOzkOFpY8eKS+26WEmsgnFScylEmeMDNWyb/jka/XpHjMxHMSHL1M3nKTPGhs8od/SzdQxs17f5DiyrgzQMXD1tVlBWsve8PY+OeAs51T6NbD0B6FvhKBEZNcC2pXYkKa/mqtCm5xspel3A8gDTSwPacrl0rNTyorq5cphUktBzAZois/hLW47Av2rSDcHBd0ELku24TQaJvJ5wfQSYWq+oMGIcgTXpnPjRh511yWcDs28SKE/buudN6Ghh4RpYUo+GALL0Csm1qm5RToUp77O2fYMHUs+wLpYXB7XJx8vwhlaeIUavB5aDoGyWsUjNIrp6V0pA2zYEaXFyqvXiSWsTFQ3zXjVvSybmuJTQwqZvllFV7B4MGy/doqhpG6a8SxHDyii8S7BhUa/nTilL6drhkVLnSGVGfofcJbhfrSgs8KZAFHpFabthC/zfT0VNRiCrequg0ZArwICAJf3BDnlyndWJ688/eKHLWHkrlm7VSOXyWfPxr8iXH/lJa0lLK1/oQoj9df63l0PjOStY/dsNHDZ8k3nH6z5nj0IUwfprkHV+/3a8Qja3AByM0tyB7wOodPUQ1zat/MXOxfeQ==
  template:
    metadata:
      name: external-dns-helm-values
      namespace: system-ingress
    type: Opaque
