apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: external-dns-helm-values
  namespace: system-ingress
spec:
  encryptedData:
    values: AgAyAuXGU8YtfrebjxwR3eKnAsIrkC81zdUEOx5mmm0e4pq861AhT2lZ2X9gH96Z0VImKEiT+DCrpeDY3ro+Vfn7mFaVHXLUQnvg1AQ/Av33FspdgYVC0J9Fxy37vPnjPkTXM6QIun9m1Jegqo4p03qn8bnMh+VHiE80PuaYE0Gp/W3CAhgxlIhTKZTAlAL9MnV7hkGdcKi3tC7/+fp7zbvbrAz8QZ0KQAiElJFvOSf/5QSxBOdTeiHo2P2X7/Z8EjJtMfZqPcsKFh14R4b+WuYKfMTn2sUJ6fwJmfXx4k4LahhY6pWUMC0Lx3ABC5g6xBe7Qvpn5mbs+ZxegRvgff5SxXo/0kpGUNV9bEQfUCT69nvdysze3dqn8xeTWIX+7S8OwxgqoctokdbaGE6IFfOp22YPMRHq6ZY7xZIw1wpAbtwETGFNvoUMXWHVaEUzHD9eUANo/Nn7K/ATlxlM1K5TDVjR8FHqsV0ZXOYXk9egvMI/awa6DUz9e1wHqxPZG9oZ5N+WrfTMD2/EBrTiwJkQww0rifgiaddzusfCK/TyDbiKEg9JKojidSOHAsGl7PLcs+gz6l61VH6Osn1D/BMtT76DtNhZFWTaHTkkH392LTWHhMPnYk4Zi82xhpZ9Tlj8SO6txbccgHlp/aby2FhqYnRrYaOn1j0rPQUHduGWHU/192yMHnrLIoRCzxmTfcPDmKmXy5tlXCp1E0vbsSLh1yn485J9KBa9iKxqHh50Q6GgWn1e8ZxWKNx6yuswAYXLzc7q4T1uuVfVZoY6EX70ELz4mQfgIq0JonHACjfOxcEUaSLbLCFoeCNWmW3QSsG2Y64CK/lc3S+L37BtdlXnoIWXKEvbBud7jzSpYg==
  template:
    metadata:
      name: external-dns-helm-values
      namespace: system-ingress
    type: Opaque
