apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: external-dns-helm-values
  namespace: system-ingress
spec:
  encryptedData:
    values: AgBPw6vCs7zVmwEt2dAib5mm27AcI+aNS4fSNug7hYHCEsHTN03iCLTH23bPM0G5jTaLq6cICe69klYEc1j4nVpOhuENsZ4Qff+X5+7x1RNxAo/fljCmJxbFfrfP/q0tLm+arjMXdJ5X/73IsKyi5smm0x58/PTemJk3ag4ay9ZgWbQaMOCBOjpsQrCtc4PcLkHkpboWxLnO6iYazys3TILCECnPQK9j68+NAbcSK/6YNtXJYzbgudYHB8DBLfrZ86BcaumqeIwLdJXDROdNxOwxEv98+zHsd9BvuJF1mMn9jQJVfQ4Ql1lgZQaG2R32SnT4raJOsUYnd59j7GTSKfLiMPHGPCxjbVHJVCJI1dzmdxsHJnjeTAxzDYYoczIldObv5eAzowe+yDW3SfwtakO8fsdO2MDaGqjU54N/obvNNHNOyR5XM4v5t0ZpYfNF97gV17/ayFDzIiW4SsxzLC+/j++DA5nCC+ma9IgCzMC/ZGavsrp+VUgNVHWKjyUbCrvkI8yr8tHwMAeuBOMYw1VJ70rzfYpG18hNPkshWI0pUoNN4odCJZidLTEDdBRfLds+6P68AHoLO8aHIdG9x3r17LbMWnlklKXV40j1pJSWCIT84NqBWQc3/jjm9PZO/1+z83dpd7M2IzSy97Gz6z3s1VLtVMRtpS9RWo5KjoaH5PM8tyWR6XvGnVEbDuyILIoDCXUuOuEzyxjydeDVCmARqMQNwspx2qR3iH0DJ3v/Yevztuvov67XYFjURzqJcs/HJGw7k6iy9NSlmxQeYZXmnE/TJIoY0SLLz3tppN2mIcY5Ihpz7BuCUACG5eOjd7FFOoLh8FhXtX5dUPK1yNVRr0REft/LDCSLPm8e6A==
  template:
    metadata:
      name: external-dns-helm-values
      namespace: system-ingress
    type: Opaque
