apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: external-dns-helm-values
  namespace: system-ingress
spec:
  encryptedData:
    values: AgAnTSIC3gss9zCcwQIKMQDH3J5Y0A2xl0fP4+z1yozyZcK0M5A5GIQb1I7t05uZXBhi7S6ckczKAXKVGnBxHDZYEw6iOAlbJgqBpaefmk09xL/5dV2epAqMe52ZbKpn3E7/CoBE4TTNbcRUupGOALy5TWPcWmGD/KHo2OnNJWmIyGL3CEM31UcX4NtKqY9Tnf3U51Oxs9f40zNtmt5klv8OfA/iWQ1PTVgAi3hY2lnZf7Y47wqJobpjDDqSpmRLRbDVXS5eieYD0nlkjZsDERqVROXfrh21nBlb8t05HlNQet3z8i/v8uNfPDuGC8hXkdshlMy04lqnXyxnaHg7383teZKl17vyAQBXiOeS5OQjteNei7Cu5Hc9OSj/NQsN2PWgFPEIL3RgM/WF6Xl9iYSpKmNgC1Z97L2YVKF+U7CObO6ptx6bTZkKr3QIi2GqcKTVgxFZObi/7kM/AOxNdHTr06flB7xF4r1cw12l2Ckm4S8YczLblVBIRnO+JzuMrewS+ps8js4FiT2oxpA/R/6R5D69ySWmxlMjkjjmqXMzQOlIGB4QnuCTf6FEJlpxJR+65jQqCJsH/JvDfyMqrg3stHLlYKi1POHVhFXMyjLDqArE9dlKazimousFzZaMgzPiIs8yfbLUDzb5YM2Kw2mYOxjNYZaHalaRdxsoYJXYKTM9yHFkmZdRgvnWZT3wDHWL1OcW0MJa5eCKaPWQTagyStxa7BUoyEp6OudgzaNHguSUfC2KzpU3bcm9091YAm17C5Bk2JjoWDzuVB4P67ZPLjO1monsNfyWQJ6hkwmoZukZOANcE3jrvF2doKQ3hIG7cqLXA8LPRWtE3A3qaRdHISyaW5cNegJYzApsNQ==
  template:
    metadata:
      name: external-dns-helm-values
      namespace: system-ingress
    type: Opaque
