apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: cloudflare-api-key-secret
  namespace: system-cert-manager
spec:
  encryptedData:
    api_key: AgDAJaQ/oyyRYBkIzvouHvy0r14V0RGkX7xdjCpk5EAQm+bg/VsjEsgvGvT9uaFmF0tC9X7FgQs+cVy8fp23Cbc2OYIjTHHw2YWTK4FncFIZRuH0tCUuCXduHGufHjLSrUdsovfKmf/5lBkSZ9RRTgxvve5Ttj2wtgW2mtv3tofdcA6EMQJKymQqv6FNs09/dcisbFUy4Fpz83RvY91a4FKM9VtQaIz0awBt4+q0AHDqTNmo0m5gSlvjZo30+KPYRDK1TGJXlqVT8t0y9SxLVq2q6REOGnSb3UPYqyCPd8KCse8lE6oenLdgqeaIUZAcAQLPWwyPRjIYEyTJC6Xxx88Jcpm8l5ANmUFZqpiPXtPOzfhd6tw4s/zioEjfHQUiFE2ZGceRncvqJKAuCsb7nxXyLOw1gDKTBJwELyy9jMebLT6nwNlbPcsf7tsG/MrHew8ZXBDwOGQzHWjmh2BXbiULwqpFc4xCYczOQHhaok0gO5b1AztC5Eq8j7S6NiIVy2Bzc+FQMJXrk7pH4bjpNSt7Uqte54FpD+StPw6BpxX5CQ3nAOljJHC3NgdhIRbvOIxePPLNuCtSQaxA24LQXDb9wGKbj7nKqYYMoMFQpfXnpJv0qmpyVIA0uhmcXWJpXnZowS3CHD37yHljZPybYV5Z8NjgKI6QdLxvK8vT1aGCeiM03A6TSfSCyUwigQU4hFxlzGRTIzRQJORReeHdlAqwXdChNWLev4/DnGqRnIXGZlIphsWa
  template:
    metadata:
      name: cloudflare-api-key-secret
      namespace: system-cert-manager
    type: Opaque
