apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: cloudflare-api-key-secret
  namespace: system-cert-manager
spec:
  encryptedData:
    api_key: AgDYtXpuwk061MPEB6PuCPhVdpyfsmd0MEXsNZ/ba42u+gNED5826UZ4R52YH0DtsgwS3idxIIVd/iivF2nK/MjiAz/yuUjPHOFDo4jYDYcyVOb6CWhm/VFUSu8iVa5Hr3VSW7k9kSCRjcPFXJdzjyZcCV6+j1WbDVo4zqU9Ud/qK4ZfAgvYdXgee9pwfPzVIlVarNZ3lz93c9BmYq5ijvXNB/wn3EkTV/qEsxMq/ZVAt9oWgi7sPfQoyDkWt/feFeQw8yumCTFZSWfhSlSH5tOh4oXbQMQWCzg19+672tNmVtruHuA7GBgDIQUajQ388tOynJh8n7WQ54Ks6pAubd9Xr0/Zvk5CFMo++NRZja+4yluVJbKDXxSVlOf3SACrfLdjBcwILj+JpczUfSq4fmW47SogSXDeY3vTawR9ar14Oj+Dn+YBiv1TFEG6l/IOrFmHc/IWk2BePd/E5hVMK8yyF3UBkHnv2gH+bcTCNybMDW9dbDlQU2T2gu6A+msMlc7B5vkB1WVFr8R2WyuXkR3wpPrg9tbjj46HWk1yxDnJtScB+RXM1vxpj0wHn/IAXfn1jO18nEMc4LJqCbqzAnYLb8YfesyKfnilKFjq5tBTvvu/qDbXvW0cfXyrU862jVyOPckYxkgiRWxkp0GMZYWaD5l+bpHDXSI3ZDQezK44Ql22BVxq9BZy8DBhW2PEZjxieRQJE6oMs6W3PKP0JgLy9Q66/GXDp8yJFOhWc4ku/xKpQkCr
  template:
    metadata:
      name: cloudflare-api-key-secret
      namespace: system-cert-manager
    type: Opaque
