apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: cloudflare-api-key-secret
  namespace: system-cert-manager
spec:
  encryptedData:
    api_key: AgA05nodLrpl9psztYtTtzzeABuKw8wtwB7JB6iQ+0VmVuUaDqLbjLL6qHNVgnTURTShffVmkPft9lC3ok7uChis4++rXY8E8Esglx5izQrPl4FxQNnp8c/bXce73UFNpue3eqLJ1p+AMkf/WgRkIghko2rRGfIdwJgcVVyjthIto+car1TB+hrj4+nrQDiNabOVVQeafW4kxhdAxo0KhNwPbsAodwDj8Vm8quxmoxI7PXcynso2LGw/0nm5TSs+H0w2j6Tv4erL5+Qtg8bXgs2RaPMfEjRACz1cfVVNsPd55RLjvZugoUdwVrffXUeiTnRKtUAaEkwk6kAF58Fo4ByaGFzM89whUkogK3AqN/94l3h4w8g/hqM3eiWI2vbYAFjr76ITpxVMl2pRO21EM9SCrJexxonW0RAKQEdXUcmCu3tpfk0BLnROJSYF4Y+0e5h2NNlTAmEsigFEz/cMflSMRDvVHPw8ElUmFUnmh8WM9pVSpWgBfAzwY2ti7cyukuW7uq7lXvC1psd6+0C1AT781a+cMGp4JHiZj0NdtPwOjKrhmOKVenKrhhVKb8UTFl5rokgBzat3Nt9jSEnY/HgnptYkdr/8G/se5P+8FlgGaO2/3mo7u7fvzOyGcO/ywCI4M5J5kJWpj22+ydwEL57LYhFB4p+bB6i5M2b6fS0Bwn966gKTWzqKFjnutj73uDe63zmdH9dKLMzvLxiIs3FwmYyvdtsL5MWQWtqIIzyuExX3IQarPA==
  template:
    metadata:
      name: cloudflare-api-key-secret
      namespace: system-cert-manager
    type: Opaque
