apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: cloudflare-api-key-secret
  namespace: system-cert-manager
spec:
  encryptedData:
    api_key: AgB5KkKIYiYr7dZ0WsUgD6Ptd5X1mhvcnbt7Me4+Av5vWOCjvYpczDM/Qghv0e7owjJHwlJMB9h+aSJTZlRCgQqNiSqNVfq9gV+LFY2/l73y8mrKnkFL1CA9heVnkDTCVuIRHxpocNT97SUS5XOZ2MohlWFV8D1i9IDKGp6Tv48JLIC6psxduFVXcV4l35u3DqJj9GdQarp5WGqxiK27nSe3EfY9G1Qx2Ah5ybb+HdfPgT1TQ6AQ6yxkkLyw4awj/Dp9bwdOSMpW5i2yOX1eNm+wJkjv85u6kD5AvZMHwNMQhZNPlyDZMCKFRqKZ7y31MuyCxyrRGfmlq4Lpr7CQTwGlW++L3FaN9fkBwLTHgMWLXqS0+ZMP3zPXLJq3AMidGNhyTSsdOI7L+zFJXHoosu7yB8jcDOw40GUXhpFR5wlbDgfuCegTwTasV0qVqlohcI3Ekq+sq9CbGCtIVHXJ8E//6I7tQAD07jhrotEDJ8ELJenTQe0r4Kq9vFVMoTc9MZW7UJ1hAMWc0DQzYQCmWELsKjKK4MZJR7p02yamSKA05XnGE/+AUxMU5nP6i6Vm8vGyLl9BsCsbnAJcynUG1jPcgK0n1PweeuhjTpC0c01mvVg6JPlPxTepXAX5B7alN8W8srv0wDpcNSm+e5HJ4vr0uLyUUJl3Yqg+c3/B+vK4+CMkSSsCtgh6lHn4OIRBbEsiVw5AlkOSjjtApgv9jqEsJiWsepJTJm/52ZeiSaW9ucOF5TyyBg==
  template:
    metadata:
      name: cloudflare-api-key-secret
      namespace: system-cert-manager
    type: Opaque
