apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: cloudflare-api-key-secret
  namespace: system-cert-manager
spec:
  encryptedData:
    api_key: AgBnj1HDoZ2h5EL2xNYKg79h37ST/0F0Sm9GMwD0aKUBnr9yxJjD13jbEYtPzR2WgLWdVNoCSkNXYaKi4Z2g0AFQhqV5+c9DO3ayXMBrzIQU8di7HuuPipIMQN8Uh082kkMdzkjVR/lVV5n8XP7vGceOzfiswi2Ja5USG3DRSoG6f5QmHkcb2sR/YH8znl/0RZs87N7ZodgqG0XJWmfGd7dRTqg2rp9Lh3sCD0WaqZS/XctzR75BlHtYWcg4Ak1t6e7V5jyarqrrGHBoz1pPH0zSOFzlaTiuJEGtosTzoBuL7Y4NR7HpwD4lLM7ar34L7swlj3SdCjrqlyEi205kSMxRiAEiwqDE7wntzx1zn1Njd1XqiSkoUELbj3PlCT5D6SIdJMO0gNDjup1I1WCmAAtNUlyW5ocJUIcKncWfpsVJqyTSnG1yhYWME1ni1bhNPAtARU40z8OG6a+/WJyOYAnrzbB4OPL0QZkuwR9zJVYufwae36tjbmc6nUC/gnTjSLv7pF2YS7GqcFYS/2+cPWbd0Ac0MqgBTCVQBDIqpUDSJVz4RGGfbo7mW1uwpO+xHdXaxliHex3va/1OLVyNISoWYrh1RqbugbiRpapnLxPMRZ8pWtz1o4zeXC7J47oSGP2w/17SkZHQCVEi0GFn0xMIcmUnKZDiLQzInzs0aRhviDUfOhRCL9GN8ldWui8yUVhM4yACE3YoxCVXYH+qiLmcWlN0Du7WVVPpRcU0qFmL5gymMAW8
  template:
    metadata:
      name: cloudflare-api-key-secret
      namespace: system-cert-manager
    type: Opaque
