apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: cloudflare-api-key-secret
  namespace: system-cert-manager
spec:
  encryptedData:
    api_key: AgBL8MN4xQHHdkVIOniZ4oV4h+iUxU8EizO6zuUMXENnmyzT3mmqc799jjfFXayBuGG308dnz4U/qrZVEa7+gCp/qYtFt15Lpp4PX/hYXhqeX3juCAq2vJP6ntFZOSIvzc0VBtsvhEwbcnin6vY1MCX2rI3pyonKSflNOe+luu9C2OJOQJq/+jHLo+vggySeCITfwd9eDtVZ2V9YaC1i/05Wzp6y8sNWtpsZqDa/T/HW8Z5j7ZlUtsXZXb7V3Wnrf1NNhl/SG+uYNZaRgVTpd/YL4oNIpAKTrrLdNolJO8KfC0/yNO0FGahsncngWaP+0mhDF+c9WWGtoFXD6cpEaRnoV1qHFeWQd+4WAMUa2DQw4RWsQu1DzubkJyG1Q7cJUooBKoQ2MFE6jHhvz2IwgTMbH3SkwkRMelVyE4z6NC//GD2OAef1hBoO0tu1ZHdGnZF27prCuMkEEf3nhl2PkmTpdA9lmwg/sYBNAqhoM67Mey9ubo8iPGiNi1elRnNgKFUxwZ0a+1Casv99e8LtVRvo/GaExUGl+3WglB1bj5R4ZOVnChqR0Qjyundg+vxjYnOT1BLO6lcPUqw6zc4NyJMk+TB1zqWHraPBUVFT1C+IhhutHx9pAX97asCF+XgAe7Owf28XjpU/db8UgK2mbwBgtYFklkXuu7amU36k7xKcOWQqqrYySFqQsXI3HR3fSSIrznG6Bwn+eLn59qu7DHZ9UmtlcaEU0qiRnhws2Q1Ihc2Gk8u4
  template:
    metadata:
      name: cloudflare-api-key-secret
      namespace: system-cert-manager
    type: Opaque
