---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: ingress-nginx
  namespace: system-ingress
  annotations:
    fluxcd.io/ignore: "false"
    fluxcd.io/automated: "false"
spec:
  releaseName: ingress-nginx
  chart:
    repository: https://kubernetes.github.io/ingress-nginx
    name: ingress-nginx
    version: 2.11.2
  values:
    controller:
      image:
        digest: ""

      config:
        use-forwarded-headers: "true"

      replicaCount: 2

      metrics:
        enabled: true
        serviceMonitor:
          enabled: true
          namespace: system-ingress
          namespaceSelector:
            any: true

      resources:
        requests:
          memory: "128M"
        limits:
          memory: "256M"

      service:
        type: LoadBalancer
        externalIPs:
          - 192.168.26.1
        externalTrafficPolicy: Local

      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            - labelSelector:
                matchExpressions:
                  - key: app.kubernetes.io/name
                    operator: In
                    values:
                      - ingress-nginx
              topologyKey: "kubernetes.io/hostname"
