---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: ingress-nginx
  namespace: system-ingress
  annotations:
    fluxcd.io/ignore: "false"
    fluxcd.io/automated: "false"
spec:
  releaseName: ingress-nginx
  chart:
    repository: https://kubernetes.github.io/ingress-nginx
    name: ingress-nginx
    version: 2.11.2
  values:
    controller:
      image:
        repository: k8s.gcr.io/ingress-nginx/controller
        tag: "v0.35.0"
        digest: ""

      config:
        ssl-protocols: "TLSv1.3 TLSv1.2"
        enable-modsecurity: "true"
        enable-owasp-modsecurity-crs: "true"

        use-forwarded-headers: "true"

        proxy-body-size: "25m"

      extraEnvs:
      - name: TZ
        value: Europe/Amsterdam

      replicaCount: 2

      service:
        type: LoadBalancer
        externalIPs:
        - 192.168.26.1
        externalTrafficPolicy: Local

      metrics:
        enabled: true
        serviceMonitor:
          enabled: true
          namespace: system-ingress
          namespaceSelector:
            any: true

      resources:
        requests:
          memory: "128M"
        limits:
          memory: "256M"
