---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: ingress-nginx
  namespace: system-ingress
  annotations:
    fluxcd.io/ignore: "false"
    fluxcd.io/automated: "false"
spec:
  releaseName: ingress-nginx
  chart:
    repository: https://kubernetes.github.io/ingress-nginx
    name: ingress-nginx
    version: 2.11.2
  values:
    controller:
      config:
        use-forwarded-headers: "true"

      replicaCount: 2

      resources:
        requests:
          memory: "128M"
        limits:
          memory: "256M"

      service:
        type: LoadBalancer
        loadBalancerIP: 192.168.26.1
        externalTrafficPolicy: Local
