---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: node-red
  namespace: home-automation
  annotations:
    fluxcd.io/ignore: "false"
    fluxcd.io/automated: "false"
spec:
  releaseName: node-red
  chart:
    repository: https://billimek.com/billimek-charts/
    name: node-red
    version: 2.0.2
  values:
    image:
      repository: nodered/node-red
      tag: 1.1.3

    affinity:
      nodeAffinity:
        requiredDuringSchedulingIgnoredDuringExecution:
          nodeSelectorTerms:
            - matchExpressions:
                - key: role.home-automation
                  operator: In
                  values:
                    - "true"

    tolerations:
      - key: "role.home-automation"
        operator: "Equal"
        value: "true"
        effect: "NoSchedule"

    enableProjects: "true"
    timezone: "Europe/Amsterdam"

    persistence:
      enabled: true
      storageClass: "openebs-jiva-bjws"
      size: 1Gi

    resources:
      requests:
        memory: "256M"
      limits:
        memory: "1024M"

  valuesFrom:
    - secretKeyRef:
        name: node-red-helm-values
        key: values
