---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: sonarr-helm-values
  namespace: downloads
spec:
  encryptedData:
    values: AgC9ZdkgVnBFScy5qMl/qR3Pg0abD0gB67duzxzp/UJMd0QZVe4ut9iFk5ZL9SMC/ZtB37RFq08KsW8ojHtVM9sOf6H7qd2M1u7B5/X/PS+wG9k3OvARbGNCDuSpWxH9cIYf5p4evxl6+zbgtwlND1GFSX/aGimb4f53Go++bvAHmx5y7wR6HlZ3FTOrqrGBXi8AEAIzfgtwAkkxg/QvIN0RD3AbIKEn8JRIMG44v3jLhJeB/Uxebn2mQvqBqzakFjsA3RhvcJYnu8ZzKsfA9OUSOtQedlkMkn/UA2NYUrW3lJwEWQ3nfrW1ZEyzW2GganfYwVUqWyMmd3s48TMOZIIoM1BphMDWDf2KX2yyS4DtEADQlf/6FfOZm17Cqee4fdq87BhF/JF3Z+GN80aty/yd75ZiQ1iPjLfGoNXix3pI8dUnzdYT+DR9dNPFiUF4pX8GnAV6uTACskVJyaS1MqRpElS/53P9abteqm0bYTueRsh6laVqsurHapGujIZTjOGhtErVYWY/CHVe+XMvyDGSuSp5TU9YfY6R0kY0iOhXo98cEFdTBBb4LruqYPeSMw7zRTJfnHpXivZJ//T6qf2/VjlN57aJKjfCFZNBc5kryLmZZ1BFwlthDLwUEdLxZLfFjTG7lHz6BHptuzfH+mik9YryCG/zRyZyyyt0VDM4cMMDlUG7ngN2GbBYoTsKeLl9lVrFU0w21BwLgCIvorpxa3Q7Qh9wWpDmBmIOCQGinQhYnyoM0tDitUh10kD0i6dHWXf+Cin4Meh+UdkemOGV6ZleEtW2Sn2YvIVB0jLFFz9VN/5VeptK11cgYSA6dTknJMZw8ZK3oSt3tuTzpraiofGdxmVfGv+1XAuiftf9P4L6ZV0zNjbFJIoEcZdDDRGaivXvykJDvaLeyfqKv8KaINnbo/xoeIYIIUi/PkA=
  template:
    metadata:
      name: sonarr-helm-values
      namespace: downloads
    type: Opaque
