---
- hosts: all
  become: true
  gather_facts: true

  vars_files:
    - vars.yaml

  pre_tasks:
    - name: Install Common Packages
      apt:
        name:
          - curl
          - ca-certificates
          - nfs-common
        install_recommends: false
        update_cache: true
      register: apt_install_common
      retries: 5
      until: apt_install_common is success
      tags:
        - install_packages

    - name: Clean up apt
      apt:
        autoremove: true
      tags:
        - install_packages

  tasks:
    - include_role:
        name: system
      tags:
        - system
