---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: vernemq
  namespace: home-network
  annotations:
    fluxcd.io/ignore: "false"
    fluxcd.io/automated: "false"
spec:
  releaseName: vernemq
  helmVersion: v3
  rollback:
    enable: false
  chart:
    repository: https://vernemq.github.io/docker-vernemq
    name: vernemq
    version: 1.6.3
  values:
    image:
      repository: vernemq/vernemq
      tag: 1.10.4.1-alpine

    replicaCount: 2

    statefulset:
      annotations:
        secret.reloader.stakater.com/reload: "vernemq-secrets"

    service:
      type: LoadBalancer
      externalIPs:
        - 192.168.26.4
      ws:
        enabled: true

    serviceMonitor:
      create: true

    podAntiAffinity: hard

    secretMounts:
      - name: vernemq-auth
        secretName: vernemq-secrets
        path: /vernemq/auth

    additionalEnv:
      - name: DOCKER_VERNEMQ_ACCEPT_EULA
        value: "yes"
      - name: DOCKER_VERNEMQ_VMQ_PASSWD__PASSWORD_FILE
        value: /vernemq/auth/vmq.passwd
      - name: DOCKER_VERNEMQ_VMQ_ACL__ACL_FILE
        value: /vernemq/auth/vmq.acl

    affinity:
      podAntiAffinity:
        requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
                - key: app.kubernetes.io/name
                  operator: In
                  values:
                    - ingress-nginx
            topologyKey: "kubernetes.io/hostname"
