---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: unifi
  namespace: home-network
  annotations:
    fluxcd.io/ignore: "false"
    fluxcd.io/automated: "false"
spec:
  releaseName: unifi
  chart:
    repository: https://kubernetes-charts.storage.googleapis.com
    name: unifi
    version: 0.10.0
  values:
    image:
      repository: jacobalberty/unifi
      tag: 5.13.32

    podAnnotations:
      backup.velero.io/backup-volumes: unifi-data

    timezone: Europe/Amsterdam

    persistence:
      enabled: true
      storageClass: "openebs-jiva-bjws"
      size: 2Gi

    guiService:
      type: LoadBalancer
      loadBalancerIP: 192.168.26.3
      externalTrafficPolicy: Local
      annotations:
        metallb.universe.tf/allow-shared-ip: "true"

    controllerService:
      type: LoadBalancer
      loadBalancerIP: 192.168.26.3
      externalTrafficPolicy: Local
      annotations:
        metallb.universe.tf/allow-shared-ip: "true"

    stunService:
      type: LoadBalancer
      loadBalancerIP: 192.168.26.3
      externalTrafficPolicy: Local
      annotations:
        metallb.universe.tf/allow-shared-ip: "true"

    discoveryService:
      type: LoadBalancer
      loadBalancerIP: 192.168.26.3
      externalTrafficPolicy: Local
      annotations:
        metallb.universe.tf/allow-shared-ip: "true"

    resources:
      requests:
        memory: "512M"
      limits:
        memory: "1024M"

  valuesFrom:
    - secretKeyRef:
        name: unifi-helm-values
        key: values