---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: unifi
  namespace: home-network
  annotations:
    fluxcd.io/ignore: "false"
    fluxcd.io/automated: "false"
spec:
  releaseName: unifi
  chart:
    repository: https://kubernetes-charts.storage.googleapis.com
    name: unifi
    version: 0.10.0
  values:
    image:
      repository: jacobalberty/unifi
      tag: 5.14.23

    podAnnotations:
      backup.velero.io/backup-volumes: unifi-data

    timezone: Europe/Amsterdam

    persistence:
      enabled: true
      size: 2Gi

    guiService:
      type: LoadBalancer
      externalIPs:
        - 192.168.26.3
      externalTrafficPolicy: Local

    controllerService:
      type: LoadBalancer
      externalIPs:
        - 192.168.26.3
      externalTrafficPolicy: Local

    stunService:
      type: LoadBalancer
      externalIPs:
        - 192.168.26.3
      externalTrafficPolicy: Local

    discoveryService:
      type: LoadBalancer
      externalIPs:
        - 192.168.26.3
      externalTrafficPolicy: Local

    resources:
      requests:
        memory: "512M"
      limits:
        memory: "1024M"

  valuesFrom:
    - secretKeyRef:
        name: unifi-helm-values
        key: values
