apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: unifi-helm-values
  namespace: home-network
spec:
  encryptedData:
    values: AgB33tiRzAqwoLuMBfcGWvey6O4dRzrc94uT2EE/jpGWyBUudIdNJez/cudM3T/jXvtcxEWp6qO4M1te5qfD3X5OQjF1w6BBILJHBIRcUVL1w1F466vdUuowfc0r6mH+IqVHFvEFkv90cpHcXPJQbduGUBwK4t8mM13mlBcnfxjmYlwDwUdOYkRirOrNGoDHXF14hEYEvxEiOlaZckIRWCMRun/IXn9Qx3GjKrnFaAUiEl0gprxkTdLXcQiirV69HjOtGpumDULNiRuCOtAD1+gBYrIUFBzzlw0Dpp2XffSTZL0NGBetLfRgehrMuYvPzqlSoZ4J+PmF2On/P5AVVvT8nXCg/rfWevoRGudrxc6X748KlKbT5SIR83pxTq5eThShcDOd2DTW/yM0mWnjNvPRvi1UYkC2Q5EcmAiLvjVqzUsEZQjP9ULWcVnsq7rzgJyDMOM5A7VDKbhD+iGRydlmCBEw/hIwoDMPb69KUwbCKaf0sRVU1QrwZR/QX/SVuMus942RBbfSdCvycx97DhAWvwp8i0KDZxwkPMJzozrQOyUYNvqgHPPPB4snIKvG4XKbE28DVeK6nNBR9XaYrRRFtQUJsLE5wuBX9mgfebqSmkenhR0Ch7qxvJ6O5KLPGFR75TLZwXPg1OGvvdanS/VjURYVkEf8UrY6Y5F1tsh93rtxa9PVcgth6fEy1iPjl3R7FmQGPMrmwjzG6buXaRfpTv6hN6jj5S9kveKkX603+UZ215KeIlUSoJBNO7FaaUK9LHgDfkyvveX51XLnC/eisSQmX+NK4YrZ3CSuqUZ9+ZzZe+2GekQg8d8gu0YnFeIofxyJkYUqOmSd0cD3R63cBD9I2p7XVKo03sXNT3fLwqZZMZYWPq0kCNv6vehofCjz7rIByg03KLk3wo5h5yf3JHbE56V76Yy4LfQ9VduSzIwbf3AZb5fcYbXODI+ApYCJ8t16LAJrLgBQtJ/L6O9sZ0iYn34G8/Dv/vvSB8zne4ffMHEEQ+ai/QhCURr0wRh1kYzpzavhCg9Y7r2ZlxdPUsOw8gFejwgijwy33eGkw/7yYv5gse+8XrG9YfEz5WA6lZy2jcgGS3PkcLOc2vJVriPLd+kk8Hx37Ob1kXEWL9trc+dpb9vl/AoQq0k6v+qk1R5SK+5Uk/w0MWmoaMI50xj1FMCGXA==
  template:
    metadata:
      name: unifi-helm-values
      namespace: home-network
    type: Opaque
