---
apiVersion: v1
kind: ConfigMap
metadata:
  name: radicale-config
  namespace: selfhosted
  labels:
    app: radicale
data:
  config: |
    # -*- mode: conf -*-
    # vim:ft=cfg

    [server]
    hosts = 0.0.0.0:5232

    [encoding]

    [auth]
    type = htpasswd
    htpasswd_filename = /config/users

    [rights]
    type = from_file
    file = /config/rights

    [storage]
    filesystem_folder = /data/collections

    [web]

    [logging]

    [headers]
  
  rights: |
    # Authenticated users can read and write their own collections.
    [owner-write]
    user = .+
    collection = %(login)s(/.*)?
    permission: rw

    # Everyone can read the root collection
    [read]
    user = .*
    collection =
    permission = r
