---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: home-assistant
  namespace: home-automation
  annotations:
    fluxcd.io/ignore: "false"
    fluxcd.io/automated: "true"
    filter.fluxcd.io/chart-image: semver:~0.114
    filter.fluxcd.io/vscode: "regex:^3.[0-9]+-.*$"
spec:
  releaseName: home-assistant
  chart:
    repository: https://billimek.com/billimek-charts/
    name: home-assistant
    version: 1.2.0
  values:
    image:
      repository: homeassistant/home-assistant
      tag: 0.114.3

    probes:
      liveness:
        enabled: false
      readiness:
        enabled: false
      startup:
        enabled: false

    podAnnotations:
      secret.reloader.stakater.com/reload: home-assistant-secrets
      backup.velero.io/backup-volumes: config

    service:
      type: LoadBalancer
      loadBalancerIP: 192.168.26.5
      externalTrafficPolicy: Local
      additionalPorts:
      - name: sonos
        port: 1400
        targetPort: 1400

    ingress:
      enabled: true

    extraEnv:
      TZ: "Europe/Amsterdam"

    extraSecretForEnvFrom:
    - home-assistant-secrets

    persistence:
      enabled: true
      size: 1Gi

    postgresql:
      enabled: true
      persistence:
        enabled: true

    git:
      enabled: true
      command:
      - ls
      - /config

    configurator:
      enabled: false

    appdaemon:
      enabled: false

    vscode:
      enabled: true
      image:
        repository: codercom/code-server
        tag: 3.4.1

      ingress:
        enabled: true

  valuesFrom:
  - secretKeyRef:
      name: home-assistant-helm-values
      key: values
