helmOperator:
  create: false
git:
  url: "git@github.com:bjw-s/k8s-gitops.git"
  branch: master
  path: deployments
  user: "bjw-s"
  email: "bjw-s@users.noreply.github.com"
memcached:
  enabled: true
additionalArgs:
  - --connect=ws://fluxcloud
prometheus:
  enabled: true
  serviceMonitor:
    create: false
    interval: 30s
    scrapeTimeout: 10s
    namespace: flux
syncGarbageCollection:
  enabled: true
  dry: false
