helmOperator:
  create: false
git:
  url: "git@github.com:bjw-s/k8s-gitops.git"
  branch: master
  path: deployments
  user: "bjw-s"
  email: "bjw-s@users.noreply.github.com"
  secretName: flux-git-deploy
memcached:
  enabled: true
#additionalArgs:
#  - --connect=ws://node-red-brains.selfhosted:1880/ws/flux
prometheus:
  enabled: true
  serviceMonitor:
    create: false
    interval: 30s
    scrapeTimeout: 10s
    namespace: flux
syncGarbageCollection:
  enabled: true
  dry: false
