---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: nextcloud
  namespace: selfhosted
  annotations:
    fluxcd.io/ignore: "false"
    fluxcd.io/automated: "false"
spec:
  releaseName: nextcloud
  chart:
    repository: https://kubernetes-charts.storage.googleapis.com/
    name: nextcloud
    version: 1.12.0
  values:
    image:
      repository: nextcloud
      tag: 19.0.1

    persistence:
      enabled: true
      size: 5Gi

  valuesFrom:
    - secretKeyRef:
        name: nextcloud-helm-values
        key: values
