apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: fluxcloud
  namespace: system-flux
spec:
  encryptedData:
    slack_url: AgAsXd4p2okIduD+A1B9BH5F/wJVhGTK7GccyvXjc6nUW32ej/pw/DUGV1AqmeHjoKpP/qekwCV2yeDTDop6eG3AvNfUW5L6ObjmquSBSJq90AVPzLUEVrb7Se8P+ougsKE/B/hy0XglirWTw0zrdkdCa7v/SsWoB1F/5D5K6GP3zOilD4BI2/KAOu/xtwmiXVAvsZmpt9g1rxohFWGXsx+B0zi1FIKadY24gkxx13WA+UjdlmsonkqtcsSdscpAixnhz7lpT+DXvlLObcbDxLryc/V9UrB2uwXtyJ0qmupwYBns/wxQ6CEFKZpNcrj2g6rEiDT/K6UlLaD/0Y8lyF+0mrJwb7L83kDREMFZRzz8UlH8Ge6a3tg8sQgpQpfZfDfFA/+oYL5yKGQpnNDJaqyLuwwT6G6Z2t/uKupCepJuisM1BbeyDQZqic8Wc4EQnQNBxh31U57w6gxMF9O65yjQNYhvo1hzWgIYQp3bmLIBwc6BY4olFuiT/Zct1TK1sZPIZEMZMg470iTD3xeI4PTfnoscmM45N/33SB3HJ3FvR5GHe0nQPzooJGIcrhefefVxDbIcmfL7J7egMP9GfU2QaQDGUMJ7jcl1BxTNryUtj1MREYecx2nMm4cNnSSm//pkFRy6Pi7NvjmjnT0Kh0i0MzXltkQwwaQWIFXhrzcyC/4Opp0FK80Pnomk89ABUbRF+05CgoO/w7FoFhWOrdQ3p5fniSQ8+97AMK/S2VnJhjUXDmU3Trxq69GNX3wTUYeqFw8fxVZhx8lnGJmc79mLs26svPLuBKfYlrzx5MVc
  template:
    metadata:
      name: fluxcloud
      namespace: system-flux
    type: Opaque
