apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: fluxcloud
  namespace: system-flux
spec:
  encryptedData:
    slack_url: AgDJUeL0K7V8lcvIlMdzZwkvmz1nQ+e35NIAc+7B2ecz6cBFDqw6oql/iEHKZfdZaJhdrL8Bh4tTDstUx3ihyECRZ0SBniW5MFicmi94y8hQ+uGnqlm17R6pAg2Z5lSJwDBS9CMYFztZv1MPn0euyNSz/HMxYo0kf2PEruZbbc/3en3SVKqEhu0DvQw5lRHDpuI5ul3gZ68DsOjwV+vh94ahGwmJvDoFhR8DEQ2kpjGQ5ilxDtmd4A8y6WpflyJ4Ekq+mGcW8jAbm35R5I6UP6b/1/iltOe4oe80NfJOsS4r2OQf5KEmQG7LuJZ2onUylEF7a5eGJpX6aBr4xpC6DF41/FYHXGyq+n8ImbHA08KANcZ48oLQVpb/aiH50VSCxio5flNoy8wTSG1Up0JVoJk1HYHNPR6mMWVUsRouD+prkwKIcRyjBE4ncDWcZ3Xxqk0Fq4V00YNQepzGof0z7Vsj+AgGhAff/4hot/cCYfFFYVhbEnpBZkIQztCE+D6PSkYLSYgg3YaBoIMXFJVbdpGNOHPQEFQVhPROAiFz9zg5ziKR0k41Cd/yRkxh287iLm+0ryXjSpHqz9l+2Lr71dXsmLVPJ6fq2kY5NpNPMv8isIg7C7Vm31sRcGKjbHQZshwsRB4exU8oeccKVTaA5iNxVne7XQhaUilCW8I9ycI+Cih/KNzqmutLAJwdHEltKA4g5gwIiTQ0cFy7nHFY6emneNgmA7JUb9EIz6vHjSEDpu9PqvjUr1Q0yXzJ7HqOc2N3Qfdj3O7gHM0LuXEpurZkzRiHAX14QqWHav/bCMw3
  template:
    metadata:
      name: fluxcloud
      namespace: system-flux
    type: Opaque
