apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: fluxcloud
  namespace: system-flux
spec:
  encryptedData:
    slack_url: AgA7MGWnRdYo7/Df0NNd6EtlFRre2TdiXaHaT9oOkO4lWR9R3ZAfKG1cu9sOmhntomrWa1sz2rULdOsCEpBSCjAwB4ldj5piNgkKvS7gJTbrKtivjN9Kjo1ykks8/G0AqVsZ5+v1zTOAVBfgW9WxIshrHChwWtKZK3jrNxLRB6CG75O5Ew0moS0atPgPAon+ofwj8xMpcnT4Dt0T4ZjgN67wGdV6+z8/oyz5ONayNK9pJcWaJKOdAt9t9CFS7gfJKaSUM02vcPPBR5UQyt/TIewryLvLwyFPsVXDvCwB8CV90bI0Zxg0dGWaZP+b3jv0tb9pCkh3F66Z3f6T5O8kFjag0gbYgOBVIf0OMTgdexqtxzTrGP5wqtVvZPVUxFlUjd5NPJEpNW+J7UPYAtPgP77ULSqmFpJpn1Mr4hRK1pfRq9wz7QXvnNJ97eZI5zv2Byk2eWsNVEuDCZc6Oh3Q1RhNPOz53PcmB6EewIum6M+1MUQWUdxBZ4KTamImKiErABsdHZ+ME85xqB2e35VloG4fEITRCOwOpxVcLg2ItDEWM9Ey9iB76szgC9gk4kCUTwQXHT+A/5kCsBBwb6aQcFRrhvuU2m0sjN23bcKHO1HZmSuAUTLsR4QuVj2WIp/VBOK1lXYqy/8/kDSRljBFeyqhHvjoFN6PP3ZQjHx1w/XTtsbj1fAm4gZl5wO7+7XntInyFmrXlGX/CB83jsKlouxKVFKTOvfuhn6m/FFsYbRpLut6zCMMHQQkngyqlCZZGHeDUOrdJBRdnvzDa0Bhpon0iL64roTunAtXBaZ8lmon
  template:
    metadata:
      creationTimestamp: null
      name: fluxcloud
      namespace: system-flux
    type: Opaque

