apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: fluxcloud
  namespace: system
spec:
  template:
    metadata:
      name: fluxcloud
      namespace: system
    type: Opaque
  encryptedData:
    slack_url: AgBZObXDPtwAIBa9xgdg+Ey8iA6g22zopr+d+oAV+S5uXJecOSBgYD0oTb0ZRZah20TOOB3pTpJPYqoDNZeeg4giXO70HXXjUs2Os01TQ2B7Y8w4vmP+MutGpr8rgDI1WiDArAxtrF1V48RKWzpG4vZ3WcadKoWs2kfs6mcgTruHtBKyMZll43TG2pZxyR4MIchlRNZ1i7qaRUqb29k6RD6bDN0m5ZkMayKVG9C+1AhTYE+catCMn0GF9EwB6glwcuK1LBp21prF786HokJZuTdUW+wjYqNOC8vgrQk+1GleLYYzXVM0XsYZVwl4dmBmogxxtgeUa9Jf6qEz5hN1kfhMAm8kYew/YjBg073PmTJBlZHF+mQpxpXy+rVXjaoikFLkWFbN3blwn/glRoQ5u0UJRaUKPJqWhyUU+c4iCYEjaBS9aCzb08rqfKkQTyBD5Jb4ojueyVNhetOFcIHnjCXYbkpa9M399iHt4Ab0XQIvP3lpSAHv3P6ClI2QRigO6fPfhMsHaQTBkvyf3zZEgIFFpq41g8PSxiZEu2gyKpV34BTQBwJCdqhMcYiyX7KqKKCcTPZUkFT/2nm7hmm6nkRSp4hdrzq+LI/scYCt4mjc4rFC7XDfdMOsyc0NURVjCYofRE08eJcKM9ESzZXSDLy2LxxEKt0MhQrhr/8T40GDCOzwd1dv+VdwUlVp90mAQvSmNna9X3pUHc/MOw4VXfD4Pk3rcr1sPDKWRMYtXCgQbRzNojx+ISGRr9wl5gbj0sZgPEQoJwq3Rj0ZXlI3o+apNcOMEDwKdscIdD2dcPMu
