apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: fluxcloud
  namespace: system-flux
spec:
  encryptedData:
    slack_url: AgBCqCTT+EhsC+6m8qnD9zNA9CPO94gp8dG83thZfI0s8gyX6v7Iut3sUn4DhLOZE+DzBYgkirdb4ObQkEhFl8KA4AfdH0STGevms5nJ9CLc3zyOtS/fS0TOEf+pBZ2eHLrYg6wtv40hbyDpnHw2Wb1vIPrNm6f/kBRw7k1EDQQmpS5tUxabxjLJqEqz7qjS0p2J5jXVG3E8rK9hU6pDBpTe13PJ/ZfMkpBJPUKbEiWDMqnnHBwDAPCShNPjpmGnkBub3DWxD5WWNcJ/I4tgG4vpAJTMReVkgEcwZGnL6sIuQenprWl1gbxzuHnFdL8ex50a1ffOjvJdfklSr9kqu+PAZD/cAkjg7+17X2Hmh92RWB2GPQFaO9bPxtap3mCUeA/ReWHddBBU5/nW1vh/SP+P9ybNdNZCLsDf8fVOLg2b4UXF3ONYTaDxe9aiNwhKEkGuhQuQzUvSy0HqsAxXatA3YEHuD4XMd0l5ar3DP6QOlk4m7igS2BerukfwJgv0BjEdv7JlpLrIAln73dfqw8arRsX8dZsdM39ZGRb4yY9KbsuQkHHrab9yeDhkMhBWsXlE3lsxkbGoy2maqYNUaCpySUeQQ8tHs0WvhzyiQicbujXEo/QofIjXMILexmkNa9Vcaw7WPHPZeI+d0lw3P3RnXf4wkE7RY+LJB4uYOYmnxb/RwhNxmFTBpT4MARWLtvUTeozH81fEJr2IwHjakNvA66VOoZtKHfzhsmqlr93E+dfQqzlFKKraWhoQUl3euPVzgjRmO9j0RFtB8X5GYx9Ta/dwW8any5yW+UT6RqtY
  template:
    metadata:
      name: fluxcloud
      namespace: system-flux
    type: Opaque
