apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: fluxcloud
  namespace: system-flux
spec:
  encryptedData:
    slack_url: AgDWXJCtrBqQuLHdtzWeXJxr0zVL76fw+KCLVInnUvi5m1Hdxb2dYUIWxfuxU60mKfJEscUZ+d9/QQUSQCzcKDJLsUQf3XQu8oTDZgkScAVlnuzfeNB+dIyVEExyhLPILDCOPsInkfNYdVH+Jy7VmAp+LPc1MbndY+Gv1M21EciBJqu04gA9uCRcmORnP1PhDDFkZLFFnBXDdwECm4dV9OvQEf/KwzuB3Svs/7pq8HAjRBizuPBPpVtAduDYKhjZiDVRuPZmo3ydQrf81KBUgUNDz+ts+Entf92oZSVNvslWIdEZSSPt/I0v7Nypsi3AzfXKQBhfJ/CW+AOauah1WGCe7AujGmc5cCtOPFj6CaKIFrbhXpCsxVU+DXKwvSunQx1d9ouMTIk6NUxdEdXe+YvXRrhwzTjcpOOMixp3YMJclCf05yNl6KbaFCW7IUnvZJcyAPl0MG8JjPrO6ghu31lj5B4GTyDAH97c/Qu2vGnNEakYwc7uUY5hWl1VQq92Mk5rOecNfPjWauPtetdiaxqbfxIOIrbRKxicODz8yw0pm5EHY4DDsvWgHjP7N1SYAazz0ud6CkaQQ0anVzxtrukrjHLRA1W1t61Sz4W8GFRx0ntlNWqgJ4GvoBJZwGI3iwO6/H4PMgTkD+IuFxC86teDUM3LLhXC7OpBYiJT7YHRmpCy6uA5NiF84EXrjJBOYOCynvFNEJbeev3otXjJK+3gWYvBcDobOGd1fHn1eSFAnFDHQjg5EQVbNegUKRO/rTBAi/NTdFdsND2aT8wU8tFdQxeM1RCzexhEXlDeEx9A
  template:
    metadata:
      name: fluxcloud
      namespace: system-flux
    type: Opaque
