apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: fluxcloud
  namespace: system-flux
spec:
  encryptedData:
    slack_url: AgC4SKYSbIv+x3NnyMzPZ963Uh6K3nU3ZZdrqPYIkdBYgV8mMIai7efzOnDhavfqOz3VkZJj5mLCcAbnTSweYkSX4SXMJ6kJMa+BGSw6SO25suuBVjAgd3CScmyZbZASF0WLqbWnWh5gyjPCKWXnhdxP+7YZYcCnjpFN8DzymV3rK7DzY/9yWt2mZTAXk/PEze46FJv8CKfEt3dqg6ILWas2TTsKQe5vLJ064AAIDauaAQBIn41xj4xN4X4Im4V5PSn2w27VPkUr6xyT5gmtkHJI8W3dWxrjbbyoIo7QwE15eWTrn6nsrh+jb1mvVQRybge2EYXRBi2PBiTm4wOZWqQiYg6GXFShewF4s23hnBjTNz1Kymf22oo2kO7g5c+BhUAGtVCjkFgLsAvhZYqsGm6f7MU6zixT4sx6XDrhE3rCBBNdZZsUHSkWM+7likqrPzHEsttNCy9k4DGVWeaYwCNHj/AIZxggIqInxXrZNTmXNKlJ+qBZWTFij1JaRVP+fto5TuZTPj7uv+9JwK5hEZEPDtr+Xl3mUTIuv3E0HtCBTeN8/R9Rh/M8fh6buKHc1oT+Xl9YE9wrPtLmivFGr52ujCv+Y/wg76uA1lWMK88CSwNToST34nmtFsOwMBGqDP+7dCJxUjycgSNUC0WB/AAU+NopdbNqMYQhUuOPWT7AOqwdCfm8b8N1gQbf5dn0CT3NqJMIwDAzrd4kd/HYsMikFiM37OGLtZhlP95M835nuCdTEKqUULlJuN5Pzc4I3iefkWkpCocypXLEeKcVGpyYonNAqJw/diLrR8D3EDtB
  template:
    metadata:
      name: fluxcloud
      namespace: system-flux
    type: Opaque
