apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: controller-manager
  namespace: actions-runner-system
spec:
  encryptedData:
    github_token: AgBP7LyunDcDGXlAW4wiSAuecuNqgcvkNuduC1wVm3jZJS2dPg15wogBfeVAoup16Id1cVdjSWmxpQsh793HgI/rJE6lWyRSA+yZIN1NR9eute0+7WHZoGLOIXIylgyFN9ZsohnzCHuzSFhJvkniqoFxPVn0igdWeTRtIlv/f1j7sQkBy95OsysFxzpUqgeANdP3wy3bRl793pqTClUYBVP8AMqarIgH8k9iyO9tDcX3qft+XMluAnVHCqjgQTfVzu/Rw/zPQPBMUnor3cYOyfLjcy8OaPD3i8okdUDLBQ5/+oZjGkCwj0dNMDsf8jYecvQUJMEF4O/uTHM9hkJhCt0RX4vsWNO3y8X9/swh8j//x4KDmxX09Vb3N2n/pVSiJ85S1MWCHHQxlOvzNOwRw6KsTmDpW9DjO4AvuOjSraDnlu+6Zqm9oBeEVwMyObRVslAhCmP6jKIoqBsJwdgPukeuo8IFlFo3cGpdQkSlcXj1zEQf2JLjUAeFDhPO9PpYIghjmmXgbPmKQ1DJZUgt55uWKIVoJ9JJc+x/ynGMwfHn+fcufAjBg+9SE4HN2Ld8HvNQuzURRJdzUV7RlK7Zhh69tQvrbWW9VlIjzMRpgCbONtIigQ93Xh9c5zRfZB1ukYIr06PUTTyWvP2I9416uzTQLRTiFT1e1huOFi0snS64lTE40Q+Im3W9sBAKMLalgFZx+QKOCbFXU1liFQajUFnHLqGsMJpxQ4Z+rphNRKb3hSL4XmRZYe/a
  template:
    metadata:
      name: controller-manager
      namespace: actions-runner-system
    type: Opaque
