---
# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json
name: "Docs: Release to GitHub pages"

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - .github/workflows/docs-publish.yaml
      - docs/**

jobs:
  release-docs:
    name: Release documentation
    runs-on: ubuntu-latest
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
    steps:
      - name: Generate Token
        uses: actions/create-github-app-token@v1
        id: app-token
        with:
          app-id: ${{ secrets.BJWS_APP_ID }}
          private-key: ${{ secrets.BJWS_APP_PRIVATE_KEY }}

      - name: Checkout main branch
        uses: actions/checkout@v4
        with:
          token: ${{ steps.app-token.outputs.token }}

      - name: Build docs
        uses: docker://ghcr.io/bjw-s/mdbook:0.4.39@sha256:f5939a2bb684ebf027b8423b478c20489048c23d2d2b887d9ef190f98fe654d9
        with:
          args: bash -c "cd docs && mdbook build"

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v4.0.0
        if: ${{ github.ref == 'refs/heads/main' }}
        with:
          github_token: ${{ steps.app-token.outputs.token }}
          publish_dir: ./docs/book/html
          user_name: "bjw-s-bot[bot]"
          user_email: "bjw-s-bot <87358111+bjw-s-bot[bot]@users.noreply.github.com>"
