---
name: lint

on:  # yamllint disable-line rule:truthy
  push:
    branches:
      - master

env:
  DEBIAN_FRONTEND: "noninteractive"

jobs:
  lint-yaml:
    if: "!contains(github.event.head_commit.message, '[ci-skip]')"
    runs-on:
      - ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install dependencies
        env:
          SHELLCHECK_VERSION: v0.7.1
        run: |
          sudo apt update && sudo apt install -y --no-install-recommends yamllint
      - name: Validate YAML files
        run: |
          ./.github/scripts/lint_yaml.sh

  lint-scripts:
    if: "!contains(github.event.head_commit.message, '[ci-skip]')"
    runs-on:
      - ubuntu-latest
    env:
      SHELLCHECK_VERSION: v0.7.1
    steps:
      - uses: actions/checkout@v2
      - name: Install dependencies
        run: |
          curl -sL https://github.com/koalaman/shellcheck/releases/download/"$SHELLCHECK_VERSION"/shellcheck-"$SHELLCHECK_VERSION".linux.x86_64.tar.xz -o /tmp/shellcheck.linux.x86_64.tar.gz
          sudo tar xf /tmp/shellcheck.linux.x86_64.tar.gz --strip-components=1 -C /usr/local/bin shellcheck-"$SHELLCHECK_VERSION"/shellcheck
          sudo chmod +x /usr/local/bin/shellcheck
      - name: Validate shell scripts
        env:
          SHELLCHECK_ERROR_LEVEL: warning
        run: |
          ./.github/scripts/lint_scripts.sh

      - uses: 8398a7/action-slack@v3
        env:
          GITHUB_TOKEN: ${{ secrets.ACCESS_TOKEN }}
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }} # required
        with:
          status: custom
          fields: workflow,job,commit,repo,ref,author,took
          custom_payload: |
            {
              username: 'action-slack',
              icon_emoji: ':octocat:',
              attachments: [{
                color: '${{ job.status }}' === 'success' ? 'good' : '${{ job.status }}' === 'failure' ? 'danger' : 'warning',
                blocks: [
                  {
                    "type": "section",
                    "fields": [
                        {
                            "type": "mrkdwn",
                            "text": "*repo*: <https://github.com/${{ github.repository }}|${{ github.repository }}>"
                        },
                        {
                            "type": "mrkdwn",
                            "text": "*ref*: ${{ github.ref }}"
                        },
                        {
                            "type": "mrkdwn",
                            "text": "*workflow*: <https://github.com/${{ github.repository }}/commit/${{ github.sha }}/checks|${{ github.workflow }}>"
                        },
                        {
                            "type": "mrkdwn",
                            "text": "*job*: <https://github.com/${{ github.repository }}/runs/${{ github.run_id }}|${process.env.AS_JOB}>"
                        }
                    ]
                  },
                  {
                      "type": "section",
                      "text": {
                          "type": "mrkdwn",
                          "text": "*commit*: <https://github.com/${{ github.repository }}/commit/${{ github.sha }}|${process.env.AS_MESSAGE}>"
                      }
                  },
                  {
                      "type": "section",
                      "fields": [
                          {
                              "type": "mrkdwn",
                              "text": "*duration*: ${process.env.AS_TOOK}"
                          }
                      ]
                  }
                ]
              }]
            }
