---
name: lint

on:  # yamllint disable-line rule:truthy
  push:
    branches:
      - master

env:
  DEBIAN_FRONTEND: "noninteractive"

jobs:
  lint-yaml:
    if: "!contains(github.event.head_commit.message, '[ci-skip]')"
    runs-on:
      - ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install dependencies
        env:
          SHELLCHECK_VERSION: v0.7.1
        run: |
          sudo apt update && sudo apt install -y --no-install-recommends yamllint
      - name: Validate YAML files
        run: |
          ./.github/scripts/lint_yaml.sh

  lint-scripts:
    if: "!contains(github.event.head_commit.message, '[ci-skip]')"
    runs-on:
      - ubuntu-latest
    env:
      SHELLCHECK_VERSION: v0.7.1
    steps:
      - uses: actions/checkout@v2
      - name: Install dependencies
        run: |
          curl -sL https://github.com/koalaman/shellcheck/releases/download/"$SHELLCHECK_VERSION"/shellcheck-"$SHELLCHECK_VERSION".linux.x86_64.tar.xz -o /tmp/shellcheck.linux.x86_64.tar.gz
          sudo tar xf /tmp/shellcheck.linux.x86_64.tar.gz --strip-components=1 -C /usr/local/bin shellcheck-"$SHELLCHECK_VERSION"/shellcheck
          sudo chmod +x /usr/local/bin/shellcheck
      - name: Validate shell scripts
        env:
          SHELLCHECK_ERROR_LEVEL: warning
        run: |
          ./.github/scripts/lint_scripts.sh

      - name: Webhook
        uses: joelwmale/webhook-action@master
        env:
          WEBHOOK_URL: ${{ secrets.WEBHOOK_URL }}
          data: |
            {
              "github":
                {
                  "event": ${{ github.event }}
                }
            }
