---
name: lint

on:  # yamllint disable-line rule:truthy
  push:
    branches:
      - master

env:
  DEBIAN_FRONTEND: "noninteractive"

jobs:
  lint-yaml:
    if: "!contains(github.event.head_commit.message, '[ci-skip]')"
    runs-on:
      - ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Lint yaml
        uses: ibiqlik/action-yamllint@v1
        with:
          config_file: .github/yamllint.config
      - name: Webhook
        if: ${{ always() }}
        env:
          data: |
            {
              "repo": "${{ github.repository }}",
              "ref": "${{ github.ref }}",
              "sha": "${{ github.sha }}",
              "workflow": "${{ github.workflow }}",
              "job": "${{ github.job }}",
              "job_status": "${{ job.status }}",
              "run_id": "${{ github.run_id }}"
            }
        run: |
          COMPACT_JSON=$(echo -n "$data" | jq -c '')
          curl -s -X POST \
              -H "content-type: application/json" \
              --data "$COMPACT_JSON" ${{ secrets.WEBHOOK_URL }}

  lint-scripts:
    if: "!contains(github.event.head_commit.message, '[ci-skip]')"
    runs-on:
      - ubuntu-latest
    env:
      SHELLCHECK_VERSION: v0.7.1
    steps:
      - uses: actions/checkout@v2
      - name: Run Shellcheck
        uses: azohra/shell-linter@latest
        with:
          severity: "warning"
      - name: Webhook
        if: ${{ always() }}
        env:
          data: |
            {
              "repo": "${{ github.repository }}",
              "ref": "${{ github.ref }}",
              "sha": "${{ github.sha }}",
              "workflow": "${{ github.workflow }}",
              "job": "${{ github.job }}",
              "job_status": "${{ job.status }}",
              "run_id": "${{ github.run_id }}"
            }
        run: |
          COMPACT_JSON=$(echo -n "$data" | jq -c '')
          curl -s -X POST \
              -H "content-type: application/json" \
              --data "$COMPACT_JSON" ${{ secrets.WEBHOOK_URL }}
