name: main
on:
  push:
    branches:
      - master
    tags-ignore:
      - flux-*
jobs:
  main:
    runs-on:
      - self-hosted

    steps:
      - uses: actions/checkout@v2
        with:
          token: ${{ secrets.ACCESS_TOKEN }}

      - name: Unlock secrets
        uses: sliteteam/github-action-git-crypt-unlock@1.1.0
        env:
          GIT_CRYPT_KEY: ${{ secrets.GIT_CRYPT_KEY }}

      - name: Git status
        run: |
          git status
