name: main

on:
  push:
    branches:
      - master
    tags-ignore:
      - flux-*

env:
  DEBIAN_FRONTEND: noninteractive

jobs:
  main:
    runs-on:
      - self-hosted

    steps:
      - uses: actions/checkout@v2
        with:
          token: ${{ secrets.ACCESS_TOKEN }}

      - name: Unlock secrets
        uses: sliteteam/github-action-git-crypt-unlock@1.1.0
        env:
          GIT_CRYPT_KEY: ${{ secrets.GIT_CRYPT_KEY }}

      - name: Generate Secrets
        uses: stefanprodan/kube-tools@v1
        with:
          kubectl: 1.18.6
          command: |
            apt-get update -qq && apt-get install --no-install-recommends -y -qq gettext-base git-crypt
            curl -sL https://github.com/bitnami-labs/sealed-secrets/releases/download/v0.12.5/kubeseal-linux-amd64 -o /usr/local/bin/kubeseal
            chmod +x /usr/local/bin/kubeseal

      - name: Git status
        run: |
          git status

      - name: Git status
        run: |
          git status
