name: main

on:
  push:
    branches:
      - master
    tags-ignore:
      - flux-*

env:
  DEBIAN_FRONTEND: "noninteractive"
  KUBECTL_VERSION: "1.18.8"
  FLUXCTL_VERSION: "1.20.1"
  KUBESEAL_VERSION: "0.12.5"

jobs:
  main:
    runs-on:
      - self-hosted

    steps:
      - uses: actions/checkout@v2
        with:
          token: ${{ secrets.ACCESS_TOKEN }}

      - name: Install deps
        run: |
          sudo apt-get update -qq && sudo apt-get install --no-install-recommends -y -qq gettext-base git-crypt
          sudo curl -sL -o /usr/local/bin/kubeseal https://github.com/bitnami-labs/sealed-secrets/releases/download/v${KUBESEAL_VERSION}/kubeseal-linux-amd64
          sudo chmod +x /usr/local/bin/kubeseal
          kubeseal --version
          sudo curl -sL -o /usr/local/bin/yq https://github.com/mikefarah/yq/releases/latest/download/yq_linux_amd64
          sudo chmod +x /usr/local/bin/yq
          yq --version

      - name: Unlock secrets
        env:
          GIT_CRYPT_KEY: ${{ secrets.GIT_CRYPT_KEY }}
        run: |
          echo "$GIT_CRYPT_KEY" | base64 -d > ./git-crypt-key
          git-crypt unlock ./git-crypt-key
          rm ./git-crypt-key

      - name: Generate Secrets
        run: |
          ./.github/scripts/generate_sealedsecrets.sh
