name: main

on:
  push:
    branches:
      - master
    tags-ignore:
      - flux-*

env:
  DEBIAN_FRONTEND: "noninteractive"
  KUBECTL_VERSION: "1.18.8"
  FLUXCTL_VERSION: "1.20.1"
  KUBESEAL_VERSION: "0.12.5"

jobs:
  main:
    runs-on:
      - self-hosted

    steps:
      - uses: actions/checkout@v2
        with:
          token: ${{ secrets.ACCESS_TOKEN }}

      - name: Unlock secrets
        env:
          GIT_CRYPT_KEY: ${{ secrets.GIT_CRYPT_KEY }}
        run: |
          echo "$GIT_CRYPT_KEY" | base64 -d > ./git-crypt-key
          git-crypt unlock ./git-crypt-key
          rm ./git-crypt-key

      - name: Generate Secrets
        uses: docker://onedr0p/actions-runnner:latest
        run: |
          task generate-sealed-secrets
