name: main

on:
  push:
    branches:
      - master
    paths:
      - ".secrets/**/*.yaml"
      - "_setup/sealedsecret-cert.pem"
      - ".github/workflows/sealed-secrets.yaml"
    tags-ignore:
      - flux-*

env:
  DEBIAN_FRONTEND: "noninteractive"

jobs:
  main:
    runs-on:
      - self-hosted

    if: "!contains(github.event.head_commit.message, '[ci-skip]')"

    steps:
      - uses: actions/checkout@v2
        with:
          token: ${{ secrets.ACCESS_TOKEN }}

      - name: Add dependencies
        env:
          RENDERIZER_VERSION: 2.0.11
          KUBEVAL_VERSION: 0.15.0
        run: |
          sudo curl -sL https://github.com/gomatic/renderizer/releases/download/v"$RENDERIZER_VERSION"/renderizer_linux_amd64 -o /usr/local/bin/renderizer
          sudo chmod +x /usr/local/bin/renderizer
          renderizer -v
          curl -sL https://github.com/instrumenta/kubeval/releases/download/"$KUBEVAL_VERSION"/kubeval-linux-amd64.tar.gz -o kubeval-linux-amd64.tar.gz
          tar xf kubeval-linux-amd64.tar.gz
          sudo mv kubeval /usr/local/bin
          sudo chmod +x /usr/local/bin/kubeval

      - name: Unlock secrets
        env:
          GIT_CRYPT_KEY: ${{ secrets.GIT_CRYPT_KEY }}
        run: |
          echo "$GIT_CRYPT_KEY" | base64 -d > ./git-crypt-key
          git-crypt unlock ./git-crypt-key
          rm ./git-crypt-key

      - name: Generate Secrets
        run: |
          task generate-sealed-secrets

      - name: Commit and push secrets
        run: |
          if [[ -n $(git status --porcelain) ]]; then
            git config --global user.name "bjw-s"
            git config --global user.email "bjw-s@users.noreply.github.com"
            find ./deployments -name "sealedsecret-*.yaml" -exec git add "{}" \;
            git commit -m "Auto update sealed-secrets [ci-skip]" || exit 0
            git push
          fi
