name: main

on:
  push:
    branches:
      - master
    paths:
      - ".secrets/**/*.yaml"
      - "_setup/sealedsecret-cert.pem"
      - ".github/workflows/sealed-secrets.yaml"
      - ".github/scripts/generate_sealedsecrets.sh"
    tags-ignore:
      - flux-*

env:
  DEBIAN_FRONTEND: "noninteractive"

jobs:
  main:
    runs-on:
      - self-hosted

    if: "!contains(github.event.head_commit.message, '[ci-skip]')"

    steps:
      - uses: actions/checkout@v2
        with:
          token: ${{ secrets.ACCESS_TOKEN }}

      - name: Add dependencies
        run: |
          RENDERIZER_VERSION=$(curl -s "https://api.github.com/repos/gomatic/renderizer/releases" | jq --raw-output '.[0].tag_name')
          sudo curl -sL -o /usr/local/bin/renderizer https://github.com/gomatic/renderizer/releases/download/${RENDERIZER_VERSION}/renderizer_linux_amd64
          sudo chmod +x /usr/local/bin/renderizer
          renderizer -v

      - name: Unlock secrets
        env:
          GIT_CRYPT_KEY: ${{ secrets.GIT_CRYPT_KEY }}
        run: |
          echo "$GIT_CRYPT_KEY" | base64 -d > ./git-crypt-key
          git-crypt unlock ./git-crypt-key
          rm ./git-crypt-key

      - name: Generate Secrets
        run: |
          task generate-sealed-secrets

      - name: Commit and push secrets
        run: |
          if [[ -n $(git status --porcelain) ]]; then
            git config --global user.name "bjw-s"
            git config --global user.email "bjw-s@users.noreply.github.com"
            find ./deployments -name "sealedsecret-*.yaml" -exec git add "{}" \;
            git commit -m "Auto update sealed-secrets [ci-skip]" || exit 0
            git push
          fi
